// 2018-02-13 09:55:29.534106 -0800 PST m=+3.734506463
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package feecenter

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeResourceBillsResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		Amount          int64         `json:"amount"`
		Data            []interface{} `json:"data"`
		ProductCodeList []interface{} `json:"productCodeList"`
		Total           int64         `json:"total"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api378/10772
func (c *FeecenterClient) DescribeResourceBills(options ...string) (*DescribeResourceBillsResp, error) {
	resp, err := c.DoAction("DescribeResourceBills", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeResourceBillsResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeResourceBills(options ...string) (*DescribeResourceBillsResp, error) {
	return DefaultClient.DescribeResourceBills(options...)
}

func (r *DescribeResourceBillsResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
