// 2018-02-13 09:55:27.869409 -0800 PST m=+2.069806208
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package feecenter

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeBillsResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		Data []struct {
			ActionType     string `json:"actionType"`
			Amount         string `json:"amount"`
			Balance        string `json:"balance"`
			BillID         string `json:"billId"`
			CalcUnit       string `json:"calcUnit"`
			FeeID          string `json:"feeId"`
			OperationInfo  string `json:"operationInfo"`
			OperationTime  string `json:"operationTime"`
			PayMode        string `json:"payMode"`
			PayType        string `json:"payType"`
			ProductCode    string `json:"productCode"`
			Status         string `json:"status"`
			SubProductCode string `json:"subProductCode"`
		} `json:"data"`
		In    int64 `json:"in"`
		Out   int64 `json:"out"`
		Total int64 `json:"total"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api378/10770
func (c *FeecenterClient) DescribeBills(options ...string) (*DescribeBillsResp, error) {
	resp, err := c.DoAction("DescribeBills", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeBillsResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeBills(options ...string) (*DescribeBillsResp, error) {
	return DefaultClient.DescribeBills(options...)
}

func (r *DescribeBillsResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
