// 2018-01-08 13:57:36.98498 -0800 PST m=+3.335253421
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package dfw

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type CreateSecurityGroupResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		SgID     string `json:"sgId"`
		SgName   string `json:"sgName"`
		SgRemark string `json:"sgRemark"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/213/1238
func (c *DfwClient) CreateSecurityGroup(options ...string) (*CreateSecurityGroupResp, error) {
	resp, err := c.DoAction("CreateSecurityGroup", options...)
	if err != nil {
		return nil, err
	}
	var s CreateSecurityGroupResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func CreateSecurityGroup(options ...string) (*CreateSecurityGroupResp, error) {
	return DefaultClient.CreateSecurityGroup(options...)
}

func (r *CreateSecurityGroupResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
