// 2017-12-08 12:32:46.90527 -0800 PST m=+8.147133533
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package dfw

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeSecurityGroupPolicysResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		Egress  []interface{} `json:"egress"`
		Ingress []interface{} `json:"ingress"`
		Version int64         `json:"version"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/213/1364
func DescribeSecurityGroupPolicys(options ...string) (*DescribeSecurityGroupPolicysResp, error) {
	resp, err := DoAction("DescribeSecurityGroupPolicys", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeSecurityGroupPolicysResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeSecurityGroupPolicysResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
