// 2017-12-08 12:14:17.265689 -0800 PST m=+1.297840397
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package dfw

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ModifySecurityGroupsOfInstanceResp struct {
	Code     int64       `json:"code"`
	CodeDesc string      `json:"codeDesc,omitempty"`
	Data     interface{} `json:"data,omitempty"`
	Message  string      `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/213/1232
func ModifySecurityGroupsOfInstance(options ...string) (*ModifySecurityGroupsOfInstanceResp, error) {
	resp, err := DoAction("ModifySecurityGroupsOfInstance", options...)
	if err != nil {
		return nil, err
	}
	var s ModifySecurityGroupsOfInstanceResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *ModifySecurityGroupsOfInstanceResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
