// 2018-01-31 15:21:46.288957 -0800 PST m=+2.649847432
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package trade

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeDealsByCondResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		TotalNum string `json:"totalNum"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/378/4403
func (c *TradeClient) DescribeDealsByCond(options ...string) (*DescribeDealsByCondResp, error) {
	resp, err := c.DoAction("DescribeDealsByCond", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeDealsByCondResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeDealsByCond(options ...string) (*DescribeDealsByCondResp, error) {
	return DefaultClient.DescribeDealsByCond(options...)
}

func (r *DescribeDealsByCondResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
