// 2018-01-31 15:23:19.053347 -0800 PST m=+3.515962231
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package trade

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeAccountBalanceResp struct {
	BalanceInfo int64  `json:"balanceInfo"`
	Code        int64  `json:"code"`
	CodeDesc    string `json:"codeDesc"`
	Message     string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/378/4397
func (c *TradeClient) DescribeAccountBalance(options ...string) (*DescribeAccountBalanceResp, error) {
	resp, err := c.DoAction("DescribeAccountBalance", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeAccountBalanceResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeAccountBalance(options ...string) (*DescribeAccountBalanceResp, error) {
	return DefaultClient.DescribeAccountBalance(options...)
}

func (r *DescribeAccountBalanceResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
