// 2017-11-02 23:45:19.244847821 +0000 UTC m=+3.778116838
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cdn

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type AddCdnHostResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/228/1406
func AddCdnHost(options ...string) (*AddCdnHostResp, error) {
	resp, err := DoAction("AddCdnHost", options...)
	if err != nil {
		return nil, err
	}
	var s AddCdnHostResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *AddCdnHostResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
