// 2017-12-12 21:09:51.026183466 +0000 UTC m=+1309.022233157
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cdn

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DeleteCdnHostResp struct {
	Code     int64         `json:"code"`
	CodeDesc string        `json:"codeDesc"`
	Data     []interface{} `json:"data"`
	Errmsg   string        `json:"errmsg"`
	Message  string        `json:"message"`
	Retcode  int64         `json:"retcode"`
}

// Implement https://cloud.tencent.com/document/api/228/1396
func (c *CdnClient) DeleteCdnHost(options ...string) (*DeleteCdnHostResp, error) {
	resp, err := c.DoAction("DeleteCdnHost", options...)
	if err != nil {
		return nil, err
	}
	var s DeleteCdnHostResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DeleteCdnHost(options ...string) (*DeleteCdnHostResp, error) {
	return DefaultClient.DeleteCdnHost(options...)
}

func (r *DeleteCdnHostResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
