// 2017-11-02 23:46:36.24345174 +0000 UTC m=+80.776720735
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cdn

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeCdnHostInfoResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		DetailData []struct {
			HostID    string `json:"host_id"`
			HostName  string `json:"host_name"`
			HostType  string `json:"host_type"`
			HostValue int64  `json:"host_value"`
		} `json:"detail_data"`
		EndDatetime   string `json:"end_datetime"`
		Period        int64  `json:"period"`
		StartDatetime string `json:"start_datetime"`
		StatType      string `json:"stat_type"`
	} `json:"data"`
	Errmsg  string `json:"errmsg"`
	Message string `json:"message"`
	Retcode int64  `json:"retcode"`
}

// Implement https://cloud.tencent.com/document/api/228/3941
func DescribeCdnHostInfo(options ...string) (*DescribeCdnHostInfoResp, error) {
	resp, err := DoAction("DescribeCdnHostInfo", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeCdnHostInfoResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeCdnHostInfoResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
