// 2017-12-12 20:49:26.448291528 +0000 UTC m=+84.444341218
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cdn

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeCdnHostDetailedInfoResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		EndDatetime   string  `json:"end_datetime"`
		Period        int64   `json:"period"`
		StartDatetime string  `json:"start_datetime"`
		StatType      string  `json:"stat_type"`
		TotalData     []int64 `json:"total_data"`
	} `json:"data"`
	Errmsg  string `json:"errmsg"`
	Message string `json:"message"`
	Retcode int64  `json:"retcode"`
}

// Implement https://cloud.tencent.com/document/api/228/3942
func (c *CdnClient) DescribeCdnHostDetailedInfo(options ...string) (*DescribeCdnHostDetailedInfoResp, error) {
	resp, err := c.DoAction("DescribeCdnHostDetailedInfo", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeCdnHostDetailedInfoResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeCdnHostDetailedInfo(options ...string) (*DescribeCdnHostDetailedInfoResp, error) {
	return DefaultClient.DescribeCdnHostDetailedInfo(options...)
}

func (r *DescribeCdnHostDetailedInfoResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
