// 2017-11-02 18:41:04.088540184 +0000 UTC m=+83.640826018
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cdn
import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)


type GetCdnRefreshLogResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		Logs []struct {
			AppID     int64    `json:"app_id"`
			Datetime  string   `json:"datetime"`
			Host      string   `json:"host"`
			ID        int64    `json:"id"`
			Progress  int64    `json:"progress"`
			ProjectID int64    `json:"project_id"`
			Status    int64    `json:"status"`
			Type      int64    `json:"type"`
			URLList   []string `json:"url_list"`
		} `json:"logs"`
		Total int64 `json:"total"`
	} `json:"data"`
	Errmsg  string `json:"errmsg"`
	Message string `json:"message"`
	Retcode int64  `json:"retcode"`
}


// Implement https://cloud.tencent.com/document/api/228/3948
func GetCdnRefreshLog(options ...string) (*GetCdnRefreshLogResp, error) { 
	resp, err := DoAction("GetCdnRefreshLog", options...)
	if err != nil {
		return nil, err
	}
	var s GetCdnRefreshLogResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *GetCdnRefreshLogResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
