// 2017-12-12 20:49:34.37259316 +0000 UTC m=+92.368642769
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cdn

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type GetCdnLogListResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		List []struct {
			Date string `json:"date"`
			Link string `json:"link"`
			Name string `json:"name"`
			Type int64  `json:"type"`
		} `json:"list"`
		Now int64 `json:"now"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/228/8087
func (c *CdnClient) GetCdnLogList(options ...string) (*GetCdnLogListResp, error) {
	resp, err := c.DoAction("GetCdnLogList", options...)
	if err != nil {
		return nil, err
	}
	var s GetCdnLogListResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func GetCdnLogList(options ...string) (*GetCdnLogListResp, error) {
	return DefaultClient.GetCdnLogList(options...)
}

func (r *GetCdnLogListResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
