// 2017-11-02 23:46:39.424183545 +0000 UTC m=+83.957452839
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cdn

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type GetCdnHostsDetailStatisticsResp struct {
	Code     int64       `json:"code"`
	CodeDesc string      `json:"codeDesc"`
	Data     interface{} `json:"data"`
	Errmsg   string      `json:"errmsg"`
	Message  string      `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/228/9703
func GetCdnHostsDetailStatistics(options ...string) (*GetCdnHostsDetailStatisticsResp, error) {
	resp, err := DoAction("GetCdnHostsDetailStatistics", options...)
	if err != nil {
		return nil, err
	}
	var s GetCdnHostsDetailStatisticsResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *GetCdnHostsDetailStatisticsResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
