// 2017-12-12 20:49:30.655958363 +0000 UTC m=+88.652007902
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cdn

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type GetCdnHostsHyStatResp struct {
	Code     int64       `json:"code"`
	CodeDesc string      `json:"codeDesc"`
	Data     interface{} `json:"data"`
	Message  string      `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/228/7352
func (c *CdnClient) GetCdnHostsHyStat(options ...string) (*GetCdnHostsHyStatResp, error) {
	resp, err := c.DoAction("GetCdnHostsHyStat", options...)
	if err != nil {
		return nil, err
	}
	var s GetCdnHostsHyStatResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func GetCdnHostsHyStat(options ...string) (*GetCdnHostsHyStatResp, error) {
	return DefaultClient.GetCdnHostsHyStat(options...)
}

func (r *GetCdnHostsHyStatResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
