// 2017-11-27 19:27:40.368782361 +0000 UTC m=+1.400315825
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cdn

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type GetCdnMiddleSourceListResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		MiddleSourceList []string `json:"middle_source_list"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/
func GetCdnMiddleSourceList(options ...string) (*GetCdnMiddleSourceListResp, error) {
	resp, err := DoAction("GetCdnMiddleSourceList", options...)
	if err != nil {
		return nil, err
	}
	var s GetCdnMiddleSourceListResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *GetCdnMiddleSourceListResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
