// 2017-12-12 20:54:38.696931978 +0000 UTC m=+396.692981641
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cdn

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type OfflineHostResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/228/1403
func (c *CdnClient) OfflineHost(options ...string) (*OfflineHostResp, error) {
	resp, err := c.DoAction("OfflineHost", options...)
	if err != nil {
		return nil, err
	}
	var s OfflineHostResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func OfflineHost(options ...string) (*OfflineHostResp, error) {
	return DefaultClient.OfflineHost(options...)
}

func (r *OfflineHostResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
