// 2017-12-12 20:59:43.287690016 +0000 UTC m=+701.283739625
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cdn

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type OnlineHostResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/228/1402
func (c *CdnClient) OnlineHost(options ...string) (*OnlineHostResp, error) {
	resp, err := c.DoAction("OnlineHost", options...)
	if err != nil {
		return nil, err
	}
	var s OnlineHostResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func OnlineHost(options ...string) (*OnlineHostResp, error) {
	return DefaultClient.OnlineHost(options...)
}

func (r *OnlineHostResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
