// 2017-12-12 20:48:51.843338096 +0000 UTC m=+49.839387756
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cdn

import (
	"encoding/json"
	"fmt"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type RefreshCdnDirResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		Count  int64  `json:"count"`
		TaskID string `json:"task_id"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/228/3947
func (c *CdnClient) RefreshCdnDir(dirs ...string) (*RefreshCdnDirResp, error) {
	var options []string
	for k, v := range dirs {
		options = append(options, fmt.Sprintf("dirs.%v=%v", k, v))
	}
	resp, err := c.DoAction("RefreshCdnDir", options...)
	if err != nil {
		return nil, err
	}
	var s RefreshCdnDirResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func RefreshCdnDir(dirs ...string) (*RefreshCdnDirResp, error) {
	return DefaultClient.RefreshCdnDir(dirs...)
}

func (r *RefreshCdnDirResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
