// 2017-11-02 18:40:20.559234171 +0000 UTC m=+40.111519947
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cdn
import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)


type UpdateCdnConfigResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}


// Implement https://cloud.tencent.com/document/api/228/3933
func UpdateCdnConfig(options ...string) (*UpdateCdnConfigResp, error) { 
	resp, err := DoAction("UpdateCdnConfig", options...)
	if err != nil {
		return nil, err
	}
	var s UpdateCdnConfigResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *UpdateCdnConfigResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
