// 2017-12-12 20:48:43.154896057 +0000 UTC m=+41.150945710
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cdn

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type UpdateCdnConfigResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/228/3933
func (c *CdnClient) UpdateCdnConfig(options ...string) (*UpdateCdnConfigResp, error) {
	resp, err := c.DoAction("UpdateCdnConfig", options...)
	if err != nil {
		return nil, err
	}
	var s UpdateCdnConfigResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func UpdateCdnConfig(options ...string) (*UpdateCdnConfigResp, error) {
	return DefaultClient.UpdateCdnConfig(options...)
}

func (r *UpdateCdnConfigResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
