// 2017-12-11 22:39:51.606249 -0800 PST m=+1.997156435
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cvm

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type CreateKeyPairResp struct {
	Response struct {
		KeyPair struct {
			KeyID      string `json:"KeyId"`
			KeyName    string `json:"KeyName"`
			PrivateKey string `json:"PrivateKey"`
			ProjectID  int64  `json:"ProjectId"`
			PublicKey  string `json:"PublicKey"`
		} `json:"KeyPair,omitempty"`
		RequestID string      `json:"RequestId"`
		Error     interface{} `json:"Error,omitempty"`
	} `json:"Response"`
}

// Implement https://cloud.tencent.com/document/api/213/9400
func CreateKeyPair(options ...string) (*CreateKeyPairResp, error) {
	resp, err := DoAction("CreateKeyPair", options...)
	if err != nil {
		return nil, err
	}
	var s CreateKeyPairResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *CreateKeyPairResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
