// 2017-10-05 21:09:26.043632182 -0700 PDT m=+11.851084869
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at

package cvm
import (
	"encoding/json"
)


type DescribeZonesResp struct {
	Code       int64  `json:"code"`
	CodeDesc   string `json:"codeDesc"`
	Message    string `json:"message"`
	TotalCount int64  `json:"totalCount"`
	ZoneSet    []struct {
		Zone      string `json:"zone"`
		ZoneID    string `json:"zoneId"`
		ZoneName  string `json:"zoneName"`
		ZoneState string `json:"zoneState"`
	} `json:"zoneSet"`
}


// Implement https://cloud.tencent.com/document/api/213/9455
func DescribeZones(options ...string) (*DescribeZonesResp, error) {
	resp, err := DoAction("DescribeZones", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeZonesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

