// 2017-12-14 22:05:55.457053 -0800 PST m=+2.251521565
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cvm

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeInstancesResp struct {
	Response struct {
		InstanceSet []struct {
			CPU                int64       `json:"CPU"`
			CreatedTime        string      `json:"CreatedTime"`
			DataDisks          interface{} `json:"DataDisks"`
			ExpiredTime        interface{} `json:"ExpiredTime"`
			ImageID            string      `json:"ImageId"`
			InstanceChargeType string      `json:"InstanceChargeType"`
			InstanceID         string      `json:"InstanceId"`
			InstanceName       string      `json:"InstanceName"`
			InstanceType       string      `json:"InstanceType"`
			InternetAccessible struct {
				InternetChargeType      string `json:"InternetChargeType"`
				InternetMaxBandwidthOut int64  `json:"InternetMaxBandwidthOut"`
			} `json:"InternetAccessible"`
			KeyPairIds []string `json:"KeyPairIds"`
			Memory     int64    `json:"Memory"`
			OsName     string   `json:"OsName"`
			Placement  struct {
				HostID    interface{} `json:"HostId"`
				ProjectID int64       `json:"ProjectId"`
				Zone      string      `json:"Zone"`
			} `json:"Placement"`
			PrivateIPAddresses []string    `json:"PrivateIpAddresses"`
			PublicIPAddresses  []string    `json:"PublicIpAddresses"`
			RenewFlag          interface{} `json:"RenewFlag"`
			RestrictState      string      `json:"RestrictState"`
			SecurityGroupIds   []string    `json:"SecurityGroupIds"`
			SystemDisk         struct {
				DiskID   interface{} `json:"DiskId"`
				DiskSize int64       `json:"DiskSize"`
				DiskType string      `json:"DiskType"`
			} `json:"SystemDisk"`
			VirtualPrivateCloud struct {
				AsVpcGateway bool   `json:"AsVpcGateway"`
				SubnetID     string `json:"SubnetId"`
				VpcID        string `json:"VpcId"`
			} `json:"VirtualPrivateCloud"`
		} `json:"InstanceSet,omitempty"`
		Error      interface{} `json:"Error,omitempty"`
		RequestID  string      `json:"RequestId"`
		TotalCount int64       `json:"TotalCount"`
	} `json:"Response"`
}

// Implement https://cloud.tencent.com/document/api/213/9388
func (c *CvmClient) DescribeInstances(options ...string) (*DescribeInstancesResp, error) {
	resp, err := c.DoAction("DescribeInstances", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeInstancesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeInstances(options ...string) (*DescribeInstancesResp, error) {
	return DefaultClient.DescribeInstances(options...)
}

func (r *DescribeInstancesResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
