// 2017-10-06 10:52:17.389710017 -0700 PDT m=+6.910485737
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at

package cvm

import (
	"encoding/json"
)

type DescribeInstancesResp struct {
	Code        int64  `json:"code"`
	CodeDesc    string `json:"codeDesc"`
	InstanceSet []struct {
		Region       string `json:"Region"`
		AutoRenew    int64  `json:"autoRenew"`
		Bandwidth    int64  `json:"bandwidth"`
		CPU          int64  `json:"cpu"`
		CreateTime   string `json:"createTime"`
		CvmPayMode   int64  `json:"cvmPayMode"`
		DeadlineTime string `json:"deadlineTime"`
		DeviceClass  string `json:"deviceClass"`
		DiskInfo     struct {
			RootID      interface{} `json:"rootId"`
			RootSize    int64       `json:"rootSize"`
			RootType    int64       `json:"rootType"`
			StorageID   interface{} `json:"storageId"`
			StorageSize int64       `json:"storageSize"`
			StorageType int64       `json:"storageType"`
		} `json:"diskInfo"`
		ImageID        int64       `json:"imageId"`
		ImageType      string      `json:"imageType"`
		InstanceID     string      `json:"instanceId"`
		InstanceName   string      `json:"instanceName"`
		IsVpcGateway   int64       `json:"isVpcGateway"`
		LanIP          string      `json:"lanIp"`
		Mem            int64       `json:"mem"`
		NetworkPayMode int64       `json:"networkPayMode"`
		Os             string      `json:"os"`
		ProjectID      int64       `json:"projectId"`
		Status         int64       `json:"status"`
		StatusTime     string      `json:"statusTime"`
		SubnetID       interface{} `json:"subnetId"`
		UnImgID        string      `json:"unImgId"`
		UnInstanceID   string      `json:"unInstanceId"`
		UUID           string      `json:"uuid"`
		VpcID          interface{} `json:"vpcId"`
		WanIPSet       []string    `json:"wanIpSet"`
		ZoneID         int64       `json:"zoneId"`
		ZoneName       string      `json:"zoneName"`
	} `json:"instanceSet"`
	Message    string `json:"message"`
	TotalCount int64  `json:"totalCount"`
}

// Implement https://cloud.tencent.com/document/api/213/9388
func DescribeInstances(options ...string) (*DescribeInstancesResp, error) {
	resp, err := DoAction("DescribeInstances", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeInstancesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}
