// 2017-12-04 14:46:04.751207 -0800 PST m=+1.726064785
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cvm

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeInstancesResp struct {
	Code        int64         `json:"code"`
	CodeDesc    string        `json:"codeDesc"`
	InstanceSet []interface{} `json:"instanceSet"`
	Message     string        `json:"message"`
	TotalCount  int64         `json:"totalCount"`
}

// Implement https://cloud.tencent.com/document/api/213/9388
func DescribeInstances(options ...string) (*DescribeInstancesResp, error) {
	resp, err := DoAction("DescribeInstances", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeInstancesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeInstancesResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
