// 2017-10-05 21:09:20.140541102 -0700 PDT m=+5.948092789
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at

package cvm
import (
	"encoding/json"
)


type DescribeRegionsResp struct {
	Code      int64  `json:"code"`
	CodeDesc  string `json:"codeDesc"`
	Message   string `json:"message"`
	RegionSet []struct {
		Region      string `json:"region"`
		RegionCode  string `json:"regionCode"`
		RegionName  string `json:"regionName"`
		RegionState string `json:"regionState"`
	} `json:"regionSet"`
	TotalCount int64 `json:"totalCount"`
}


// Implement https://cloud.tencent.com/document/api/213/9456
func DescribeRegions(options ...string) (*DescribeRegionsResp, error) {
	resp, err := DoAction("DescribeRegions", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeRegionsResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

