// 2017-12-11 22:29:47.725242 -0800 PST m=+2.094370013
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cvm

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeKeyPairsResp struct {
	Response struct {
		KeyPairSet []struct {
			AssociatedInstanceIds []string `json:"AssociatedInstanceIds"`
			CreatedTime           string   `json:"CreatedTime"`
			Description           string   `json:"Description"`
			KeyID                 string   `json:"KeyId"`
			KeyName               string   `json:"KeyName"`
			PublicKey             string   `json:"PublicKey"`
		} `json:"KeyPairSet,omitempty"`
		RequestID  string      `json:"RequestId"`
		TotalCount int64       `json:"TotalCount"`
		Error      interface{} `json:"Error,omitempty"`
	} `json:"Response"`
}

// Implement https://cloud.tencent.com/document/api/213/9403
func DescribeKeyPairs(options ...string) (*DescribeKeyPairsResp, error) {
	resp, err := DoAction("DescribeKeyPairs", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeKeyPairsResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeKeyPairsResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
