// 2018-05-23 14:38:05.274496221 -0700 PDT m=+2.169990211
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cvm

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeZonesResp struct {
	Response struct {
		RequestID  string `json:"RequestId"`
		TotalCount int64  `json:"TotalCount"`
		ZoneSet    []struct {
			Zone      string `json:"Zone"`
			ZoneID    string `json:"ZoneId"`
			ZoneName  string `json:"ZoneName"`
			ZoneState string `json:"ZoneState"`
		} `json:"ZoneSet"`
	} `json:"Response"`
}

// Implement https://cloud.tencent.com/document/api/213/15707
func (c *CvmClient) DescribeZones(options ...string) (*DescribeZonesResp, error) {
	resp, err := c.DoAction("DescribeZones", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeZonesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeZones(options ...string) (*DescribeZonesResp, error) {
	return DefaultClient.DescribeZones(options...)
}

func (r *DescribeZonesResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
