// 2017-12-07 12:12:12.486593 -0800 PST m=+12.932223741
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cvm

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeInstanceInternetBandwidthConfigsResp struct {
	Response struct {
		InternetBandwidthConfigSet interface{} `json:"InternetBandwidthConfigSet,omitempty"`
		RequestID                  string      `json:"RequestId"`
		Error                      interface{} `json:"Error,omitempty"`
	} `json:"Response"`
}

// Implement https://cloud.tencent.com/document/api/213/9390
func DescribeInstanceInternetBandwidthConfigs(options ...string) (*DescribeInstanceInternetBandwidthConfigsResp, error) {
	resp, err := DoAction("DescribeInstanceInternetBandwidthConfigs", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeInstanceInternetBandwidthConfigsResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeInstanceInternetBandwidthConfigsResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
