// 2017-12-18 14:43:13.348811 -0800 PST m=+25.563582392
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cvm

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeInstancesStatusResp struct {
	Response struct {
		InstanceStatusSet []struct {
			InstanceID    string `json:"InstanceId"`
			InstanceState string `json:"InstanceState"`
		} `json:"InstanceStatusSet,omitempty"`
		Error      interface{} `json:"Error,omitempty"`
		RequestID  string      `json:"RequestId"`
		TotalCount int64       `json:"TotalCount"`
	} `json:"Response"`
}

// Implement https://cloud.tencent.com/document/api/213/9389
func (c *CvmClient) DescribeInstancesStatus(options ...string) (*DescribeInstancesStatusResp, error) {
	resp, err := c.DoAction("DescribeInstancesStatus", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeInstancesStatusResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeInstancesStatus(options ...string) (*DescribeInstancesStatusResp, error) {
	return DefaultClient.DescribeInstancesStatus(options...)
}

func (r *DescribeInstancesStatusResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
