// 2017-12-11 23:11:06.127689 -0800 PST m=+3.344959287
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cvm

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ImportKeyPairResp struct {
	Response struct {
		KeyID     string      `json:"KeyId,omitempty"`
		RequestID string      `json:"RequestId"`
		Error     interface{} `json:"Error,omitempty"`
	} `json:"Response"`
}

// Implement https://cloud.tencent.com/document/api/213/9402
func ImportKeyPair(options ...string) (*ImportKeyPairResp, error) {
	resp, err := DoAction("ImportKeyPair", options...)
	if err != nil {
		return nil, err
	}
	var s ImportKeyPairResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *ImportKeyPairResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
