// 2017-12-06 18:23:07.964116 -0800 PST m=+12.498405289
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cvm

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type InquiryPriceRunInstancesResp struct {
	Response struct {
		Price struct {
			BandwidthPrice struct {
				ChargeUnit string `json:"ChargeUnit"`
				UnitPrice  int64  `json:"UnitPrice"`
			} `json:"BandwidthPrice"`
			InstancePrice struct {
				ChargeUnit string  `json:"ChargeUnit"`
				UnitPrice  float64 `json:"UnitPrice"`
			} `json:"InstancePrice"`
		} `json:"Price"`
		Error     interface{} `json:"Error,omitempty"`
		RequestID string      `json:"RequestId"`
	} `json:"Response"`
}

// Implement https://cloud.tencent.com/document/api/213/9385
func InquiryPriceRunInstances(options ...string) (*InquiryPriceRunInstancesResp, error) {
	resp, err := DoAction("InquiryPriceRunInstances", options...)
	if err != nil {
		return nil, err
	}
	var s InquiryPriceRunInstancesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *InquiryPriceRunInstancesResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
