// 2017-12-07 10:14:33.534124 -0800 PST m=+12.060434869
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cvm

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type InquiryPriceResetInstancesTypeResp struct {
	Response struct {
		Price struct {
			InstancePrice struct {
				ChargeUnit string  `json:"ChargeUnit"`
				UnitPrice  float64 `json:"UnitPrice"`
			} `json:"InstancePrice"`
		} `json:"Price"`
		RequestID string      `json:"RequestId"`
		Error     interface{} `json:"Error,omitempty"`
	} `json:"Response"`
}

// Implement https://cloud.tencent.com/document/api/213/9489
func InquiryPriceResetInstancesType(options ...string) (*InquiryPriceResetInstancesTypeResp, error) {
	resp, err := DoAction("InquiryPriceResetInstancesType", options...)
	if err != nil {
		return nil, err
	}
	var s InquiryPriceResetInstancesTypeResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *InquiryPriceResetInstancesTypeResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
