// 2017-12-07 10:18:26.004927 -0800 PST m=+13.559585169
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cvm

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ResetInstancesTypeResp struct {
	Response struct {
		RequestID string      `json:"RequestId"`
		Error     interface{} `json:"Error,omitempty"`
	} `json:"Response"`
}

// Implement https://cloud.tencent.com/document/api/213/9394
func ResetInstancesType(options ...string) (*ResetInstancesTypeResp, error) {
	resp, err := DoAction("ResetInstancesType", options...)
	if err != nil {
		return nil, err
	}
	var s ResetInstancesTypeResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *ResetInstancesTypeResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
