// 2017-12-18 14:47:25.04337 -0800 PST m=+277.257610515
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cvm

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ResetInstanceResp struct {
	Response struct {
		RequestID string      `json:"RequestId"`
		Error     interface{} `json:"Error,omitempty"`
	} `json:"Response"`
}

// Implement https://cloud.tencent.com/document/api/213/9398
func (c *CvmClient) ResetInstance(options ...string) (*ResetInstanceResp, error) {
	resp, err := c.DoAction("ResetInstance", options...)
	if err != nil {
		return nil, err
	}
	var s ResetInstanceResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func ResetInstance(options ...string) (*ResetInstanceResp, error) {
	return DefaultClient.ResetInstance(options...)
}

func (r *ResetInstanceResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
