// 2017-12-06 21:43:28.983849 -0800 PST m=+11.150918781
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cvm

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ResizeInstanceDisksResp struct {
	Response struct {
		RequestID string      `json:"RequestId"`
		Error     interface{} `json:"Error,omitempty"`
	} `json:"Response"`
}

// Implement https://cloud.tencent.com/document/api/213/9387
func ResizeInstanceDisks(options ...string) (*ResizeInstanceDisksResp, error) {
	resp, err := DoAction("ResizeInstanceDisks", options...)
	if err != nil {
		return nil, err
	}
	var s ResizeInstanceDisksResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *ResizeInstanceDisksResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
