// 2017-12-19 13:16:37.622967 -0800 PST m=+108.173763070
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cvm

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type StartInstancesResp struct {
	Response struct {
		RequestID string      `json:"RequestId"`
		Error     interface{} `json:"Error,omitempty"`
	} `json:"Response"`
}

// Implement https://cloud.tencent.com/document/api/213/9386
func (c *CvmClient) StartInstances(options ...string) (*StartInstancesResp, error) {
	resp, err := c.DoAction("StartInstances", options...)
	if err != nil {
		return nil, err
	}
	var s StartInstancesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func StartInstances(options ...string) (*StartInstancesResp, error) {
	return DefaultClient.StartInstances(options...)
}

func (r *StartInstancesResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
