// 2017-12-19 13:15:36.035198 -0800 PST m=+46.586269936
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cvm

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type StopInstancesResp struct {
	Response struct {
		RequestID string      `json:"RequestId"`
		Error     interface{} `json:"Error,omitempty"`
	} `json:"Response"`
}

// Implement https://cloud.tencent.com/document/api/213/9383
func (c *CvmClient) StopInstances(options ...string) (*StopInstancesResp, error) {
	resp, err := c.DoAction("StopInstances", options...)
	if err != nil {
		return nil, err
	}
	var s StopInstancesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func StopInstances(options ...string) (*StopInstancesResp, error) {
	return DefaultClient.StopInstances(options...)
}

func (r *StopInstancesResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
