// 2018-01-29 17:07:51.234172 -0800 PST m=+9.354902147
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ckafka

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type AddPartitionResp struct {
	Code     int64         `json:"code"`
	CodeDesc string        `json:"codeDesc"`
	Data     []interface{} `json:"data"`
	Message  string        `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/597/10100
func (c *CkafkaClient) AddPartition(options ...string) (*AddPartitionResp, error) {
	resp, err := c.DoAction("AddPartition", options...)
	if err != nil {
		return nil, err
	}
	var s AddPartitionResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func AddPartition(options ...string) (*AddPartitionResp, error) {
	return DefaultClient.AddPartition(options...)
}

func (r *AddPartitionResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
