// 2018-01-29 16:46:32.425034 -0800 PST m=+4.730157996
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ckafka

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type CreateTopicResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		TopicID string `json:"topicId"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/597/10096
func (c *CkafkaClient) CreateTopic(options ...string) (*CreateTopicResp, error) {
	resp, err := c.DoAction("CreateTopic", options...)
	if err != nil {
		return nil, err
	}
	var s CreateTopicResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func CreateTopic(options ...string) (*CreateTopicResp, error) {
	return DefaultClient.CreateTopic(options...)
}

func (r *CreateTopicResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
