// 2018-01-30 09:58:52.325579 -0800 PST m=+13.863960673
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ckafka

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DeleteTopicIpWhitelistResp struct {
	Code     int64         `json:"code"`
	CodeDesc string        `json:"codeDesc"`
	Data     []interface{} `json:"data"`
	Message  string        `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/597/10104
func (c *CkafkaClient) DeleteTopicIpWhitelist(options ...string) (*DeleteTopicIpWhitelistResp, error) {
	resp, err := c.DoAction("DeleteTopicIpWhitelist", options...)
	if err != nil {
		return nil, err
	}
	var s DeleteTopicIpWhitelistResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DeleteTopicIpWhitelist(options ...string) (*DeleteTopicIpWhitelistResp, error) {
	return DefaultClient.DeleteTopicIpWhitelist(options...)
}

func (r *DeleteTopicIpWhitelistResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
