// 2018-01-29 16:46:34.958624 -0800 PST m=+7.263752357
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ckafka

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DeleteTopicResp struct {
	Code     int64         `json:"code"`
	CodeDesc string        `json:"codeDesc"`
	Data     []interface{} `json:"data"`
	Message  string        `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/597/10099
func (c *CkafkaClient) DeleteTopic(options ...string) (*DeleteTopicResp, error) {
	resp, err := c.DoAction("DeleteTopic", options...)
	if err != nil {
		return nil, err
	}
	var s DeleteTopicResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DeleteTopic(options ...string) (*DeleteTopicResp, error) {
	return DefaultClient.DeleteTopic(options...)
}

func (r *DeleteTopicResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
