// 2018-01-29 16:28:57.19024 -0800 PST m=+3.359644785
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ckafka

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type GetInstanceAttributesResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		Bandwidth        int64  `json:"bandwidth"`
		CreateTime       int64  `json:"createTime"`
		DiskSize         int64  `json:"diskSize"`
		ExpireTime       int64  `json:"expireTime"`
		InstanceID       string `json:"instanceId"`
		InstanceName     string `json:"instanceName"`
		MsgRetentionTime int64  `json:"msgRetentionTime"`
		Status           int64  `json:"status"`
		SubnetID         string `json:"subnetId"`
		Vip              string `json:"vip"`
		VipList          []struct {
			Vip   string `json:"vip"`
			Vport string `json:"vport"`
		} `json:"vipList"`
		VpcID  string `json:"vpcId"`
		Vport  string `json:"vport"`
		ZoneID int64  `json:"zoneId"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/597/10094
func (c *CkafkaClient) GetInstanceAttributes(options ...string) (*GetInstanceAttributesResp, error) {
	resp, err := c.DoAction("GetInstanceAttributes", options...)
	if err != nil {
		return nil, err
	}
	var s GetInstanceAttributesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func GetInstanceAttributes(options ...string) (*GetInstanceAttributesResp, error) {
	return DefaultClient.GetInstanceAttributes(options...)
}

func (r *GetInstanceAttributesResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
