// 2018-01-29 16:46:33.690747 -0800 PST m=+5.995873817
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ckafka

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type GetTopicAttributesResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		CreateTime      int64         `json:"createTime"`
		EnableWhiteList int64         `json:"enableWhiteList"`
		IPWhiteList     []interface{} `json:"ipWhiteList"`
		PartitionNum    int64         `json:"partitionNum"`
		Partitions      []struct {
			IsrNum       int64 `json:"isrNum"`
			LeaderStatus int64 `json:"leaderStatus"`
			Partition    int64 `json:"partition"`
			ReplicaNum   int64 `json:"replicaNum"`
		} `json:"partitions"`
		TopicID string `json:"topicId"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/597/10102
func (c *CkafkaClient) GetTopicAttributes(options ...string) (*GetTopicAttributesResp, error) {
	resp, err := c.DoAction("GetTopicAttributes", options...)
	if err != nil {
		return nil, err
	}
	var s GetTopicAttributesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func GetTopicAttributes(options ...string) (*GetTopicAttributesResp, error) {
	return DefaultClient.GetTopicAttributes(options...)
}

func (r *GetTopicAttributesResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
