// 2017-11-20 16:24:53.107694 -0800 PST m=+4.384371862
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ApplyUploadResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Cover    struct {
		StoragePath      string `json:"storagePath"`
		StorageSignature string `json:"storageSignature"`
	} `json:"cover"`
	Message         string `json:"message"`
	StorageAppID    int64  `json:"storageAppId"`
	StorageBucket   string `json:"storageBucket"`
	StorageRegion   string `json:"storageRegion"`
	StorageRegionV5 string `json:"storageRegionV5"`
	Video           struct {
		StoragePath      string `json:"storagePath"`
		StorageSignature string `json:"storageSignature"`
	} `json:"video"`
	VodSessionKey string `json:"vodSessionKey"`
}

// Implement https://cloud.tencent.com/document/api/266/9756
func ApplyUpload(options ...string) (*ApplyUploadResp, error) {
	resp, err := DoAction("ApplyUpload", options...)
	if err != nil {
		return nil, err
	}
	var s ApplyUploadResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *ApplyUploadResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
