// 2017-12-03 02:17:14.585485 -0800 PST m=+6.594471254
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ConcatVideoResp struct {
	Code      int64  `json:"code"`
	CodeDesc  string `json:"codeDesc"`
	Message   string `json:"message"`
	VodTaskID string `json:"vodTaskId"`
}

// Implement https://cloud.tencent.com/document/api/266/7821
func ConcatVideo(options ...string) (*ConcatVideoResp, error) {
	resp, err := DoAction("ConcatVideo", options...)
	if err != nil {
		return nil, err
	}
	var s ConcatVideoResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *ConcatVideoResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
