// 2017-12-01 15:56:37.504218 -0800 PST m=+12.574009626
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type CreateTranscodeTemplateResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		Definition int64 `json:"definition"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/266/9910
func CreateTranscodeTemplate(options ...string) (*CreateTranscodeTemplateResp, error) {
	resp, err := DoAction("CreateTranscodeTemplate", options...)
	if err != nil {
		return nil, err
	}
	var s CreateTranscodeTemplateResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *CreateTranscodeTemplateResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
