// 2017-12-01 17:10:25.883555 -0800 PST m=+5.926982010
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type CreateVodTagsResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/266/7826
func CreateVodTags(options ...string) (*CreateVodTagsResp, error) {
	resp, err := DoAction("CreateVodTags", options...)
	if err != nil {
		return nil, err
	}
	var s CreateVodTagsResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *CreateVodTagsResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
