// 2017-12-03 02:24:57.039764 -0800 PST m=+40.270385546
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DeleteVodFileResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/266/7838
func DeleteVodFile(options ...string) (*DeleteVodFileResp, error) {
	resp, err := DoAction("DeleteVodFile", options...)
	if err != nil {
		return nil, err
	}
	var s DeleteVodFileResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DeleteVodFileResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
