// 2017-12-01 12:07:55.535201 -0800 PST m=+7.004749332
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DeleteClassResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/266/7816
func DeleteClass(options ...string) (*DeleteClassResp, error) {
	resp, err := DoAction("DeleteClass", options...)
	if err != nil {
		return nil, err
	}
	var s DeleteClassResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DeleteClassResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
