// 2017-11-20 22:45:09.734443 -0800 PST m=+6.088579939
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeVodPlayInfoResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	FileSet  []struct {
		Duration int64  `json:"duration"`
		FileID   string `json:"fileId"`
		FileName string `json:"fileName"`
		ImageURL string `json:"imageUrl"`
		PlaySet  []struct {
			Definition string `json:"definition"`
			URL        string `json:"url"`
			Vbitrate   int64  `json:"vbitrate"`
			Vheight    int64  `json:"vheight"`
			Vwidth     int64  `json:"vwidth"`
		} `json:"playSet"`
		Status string `json:"status"`
	} `json:"fileSet"`
	Message    string `json:"message"`
	TotalCount int64  `json:"totalCount"`
}

// Implement https://cloud.tencent.com/document/api/266/7825
func DescribeVodPlayInfo(options ...string) (*DescribeVodPlayInfoResp, error) {
	resp, err := DoAction("DescribeVodPlayInfo", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeVodPlayInfoResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeVodPlayInfoResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
