// 2017-12-02 23:27:36.511453 -0800 PST m=+27.621390940
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeVodStorageResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		UsedSpace int64 `json:"used_space"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/266/10012
func DescribeVodStorage(options ...string) (*DescribeVodStorageResp, error) {
	resp, err := DoAction("DescribeVodStorage", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeVodStorageResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeVodStorageResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
