// 2017-12-01 10:58:18.597852 -0800 PST m=+2.233114084
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeAllClassResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     []struct {
		Info struct {
			FileNum  int64  `json:"file_num"`
			ID       int64  `json:"id"`
			Level    int64  `json:"level"`
			Name     string `json:"name"`
			ParentID int64  `json:"parent_id"`
		} `json:"info"`
		Subclass []interface{} `json:"subclass"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/266/7813
func DescribeAllClass(options ...string) (*DescribeAllClassResp, error) {
	resp, err := DoAction("DescribeAllClass", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeAllClassResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeAllClassResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
