// 2017-12-01 10:58:19.781829 -0800 PST m=+3.417099132
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeClassResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     []struct {
		CreateTime string `json:"create_time"`
		ID         string `json:"id"`
		Name       string `json:"name"`
		UpdateTime string `json:"update_time"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/266/7814
func DescribeClass(options ...string) (*DescribeClassResp, error) {
	resp, err := DoAction("DescribeClass", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeClassResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeClassResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
