// 2017-12-02 23:43:15.330971 -0800 PST m=+30.929760988
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type GetPlayStatLogListResp struct {
	Code     int64         `json:"code"`
	CodeDesc string        `json:"codeDesc"`
	FileList []interface{} `json:"fileList"`
	Message  string        `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/266/12624
func GetPlayStatLogList(options ...string) (*GetPlayStatLogListResp, error) {
	resp, err := DoAction("GetPlayStatLogList", options...)
	if err != nil {
		return nil, err
	}
	var s GetPlayStatLogListResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *GetPlayStatLogListResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
