// 2017-12-03 00:34:28.81719 -0800 PST m=+17.351563409
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type GetTaskListResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		Next     string `json:"next"`
		Status   string `json:"status"`
		TaskList []struct {
			BeginProcessTime int64  `json:"beginProcessTime"`
			CreateTime       int64  `json:"createTime"`
			FinishTime       int64  `json:"finishTime"`
			Type             string `json:"type"`
			VodTaskID        string `json:"vodTaskId"`
		} `json:"taskList"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/266/11722
func GetTaskList(options ...string) (*GetTaskListResp, error) {
	resp, err := DoAction("GetTaskList", options...)
	if err != nil {
		return nil, err
	}
	var s GetTaskListResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *GetTaskListResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
