// 2017-11-20 21:54:14.911452 -0800 PST m=+24.337247627
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ModifyClassResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/266/7815
func ModifyClass(options ...string) (*ModifyClassResp, error) {
	resp, err := DoAction("ModifyClass", options...)
	if err != nil {
		return nil, err
	}
	var s ModifyClassResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *ModifyClassResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
