// 2017-12-01 15:18:18.415784 -0800 PST m=+14.422405536
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type QueryWatermarkTemplateResp struct {
	Code       int64  `json:"code"`
	CodeDesc   string `json:"codeDesc"`
	Comment    string `json:"comment"`
	CreateTime int64  `json:"create_time"`
	Height     string `json:"height"`
	Left       string `json:"left"`
	Message    string `json:"message"`
	Name       string `json:"name"`
	RepeatType string `json:"repeat_type"`
	Top        string `json:"top"`
	Type       string `json:"type"`
	UpdateTime int64  `json:"update_time"`
	URL        string `json:"url"`
	Width      string `json:"width"`
}

// Implement https://cloud.tencent.com/document/api/266/11606
func QueryWatermarkTemplate(options ...string) (*QueryWatermarkTemplateResp, error) {
	resp, err := DoAction("QueryWatermarkTemplate", options...)
	if err != nil {
		return nil, err
	}
	var s QueryWatermarkTemplateResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *QueryWatermarkTemplateResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
