// 2017-12-01 15:25:21.280793 -0800 PST m=+13.290756516
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type QueryWatermarkTemplateListResp struct {
	Zero struct {
		Comment    string `json:"comment"`
		CreateTime int64  `json:"create_time"`
		Definition int64  `json:"definition"`
		Name       string `json:"name"`
		UpdateTime int64  `json:"update_time"`
	} `json:"0"`
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/266/11608
func QueryWatermarkTemplateList(options ...string) (*QueryWatermarkTemplateListResp, error) {
	resp, err := DoAction("QueryWatermarkTemplateList", options...)
	if err != nil {
		return nil, err
	}
	var s QueryWatermarkTemplateListResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *QueryWatermarkTemplateListResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
