// 2017-12-03 01:37:24.515058 -0800 PST m=+21.426285149
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type RedoTaskResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/266/11725
func RedoTask(options ...string) (*RedoTaskResp, error) {
	resp, err := DoAction("RedoTask", options...)
	if err != nil {
		return nil, err
	}
	var s RedoTaskResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *RedoTaskResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
