// 2017-12-01 15:25:24.548752 -0800 PST m=+16.558697956
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type UpdateWatermarkTemplateResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/266/11605
func UpdateWatermarkTemplate(options ...string) (*UpdateWatermarkTemplateResp, error) {
	resp, err := DoAction("UpdateWatermarkTemplate", options...)
	if err != nil {
		return nil, err
	}
	var s UpdateWatermarkTemplateResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *UpdateWatermarkTemplateResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
