// 2017-12-01 16:50:36.60266 -0800 PST m=+15.915075992
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vod

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type UpdateTranscodeTemplateResp struct {
	Code     int64       `json:"code"`
	CodeDesc string      `json:"codeDesc"`
	Data     interface{} `json:"data"`
	Message  string      `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/266/9911
func UpdateTranscodeTemplate(options ...string) (*UpdateTranscodeTemplateResp, error) {
	resp, err := DoAction("UpdateTranscodeTemplate", options...)
	if err != nil {
		return nil, err
	}
	var s UpdateTranscodeTemplateResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *UpdateTranscodeTemplateResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
