// 2018-01-03 16:34:18.721853 -0800 PST m=+277.231360462
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ccs

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type AddClusterInstancesFromExistedCvmResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		FaliInstanceIds []struct {
			InstanceID string `json:"instanceId"`
			Message    string `json:"message"`
		} `json:"faliInstanceIds"`
		RequestID       int64       `json:"requestId"`
		SuccInstanceIds interface{} `json:"succInstanceIds"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/457/9458
func (c *CcsClient) AddClusterInstancesFromExistedCvm(options ...string) (*AddClusterInstancesFromExistedCvmResp, error) {
	resp, err := c.DoAction("AddClusterInstancesFromExistedCvm", options...)
	if err != nil {
		return nil, err
	}
	var s AddClusterInstancesFromExistedCvmResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func AddClusterInstancesFromExistedCvm(options ...string) (*AddClusterInstancesFromExistedCvmResp, error) {
	return DefaultClient.AddClusterInstancesFromExistedCvm(options...)
}

func (r *AddClusterInstancesFromExistedCvmResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
