// 2017-11-09 10:32:50.868940466 +0800 CST m=+1.718497392
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ccs

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type AddClusterInstancesFromExistedCvmResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		FaliInstanceIds []interface{} `json:"faliInstanceIds"`
		RequestID       int64         `json:"requestId"`
		SuccInstanceIds []string      `json:"succInstanceIds"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/457/9458
func AddClusterInstancesFromExistedCvm(options ...string) (*AddClusterInstancesFromExistedCvmResp, error) {
	resp, err := DoAction("AddClusterInstancesFromExistedCvm", options...)
	if err != nil {
		return nil, err
	}
	var s AddClusterInstancesFromExistedCvmResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *AddClusterInstancesFromExistedCvmResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
