// 2017-11-08 11:00:27.248011213 +0800 CST m=+2.440367781
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ccs

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type AddClusterInstancesResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		InstanceIds []string `json:"instanceIds"`
		RequestID   int64    `json:"requestId"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/457/9447
func AddClusterInstances(options ...string) (*AddClusterInstancesResp, error) {
	resp, err := DoAction("AddClusterInstances", options...)
	if err != nil {
		return nil, err
	}
	var s AddClusterInstancesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *AddClusterInstancesResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
