// 2018-01-03 15:44:12.416513 -0800 PST m=+10.232416051
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ccs

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type CreateClusterResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		ClusterID string `json:"clusterId"`
		RequestID int64  `json:"requestId"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/457/9444
func (c *CcsClient) CreateCluster(options ...string) (*CreateClusterResp, error) {
	resp, err := c.DoAction("CreateCluster", options...)
	if err != nil {
		return nil, err
	}
	var s CreateClusterResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func CreateCluster(options ...string) (*CreateClusterResp, error) {
	return DefaultClient.CreateCluster(options...)
}

func (r *CreateClusterResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
