// 2018-01-04 10:15:31.650688 -0800 PST m=+390.736406482
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ccs

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DeleteClusterResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		RequestID int64 `json:"requestId"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/457/9445
func (c *CcsClient) DeleteCluster(options ...string) (*DeleteClusterResp, error) {
	resp, err := c.DoAction("DeleteCluster", options...)
	if err != nil {
		return nil, err
	}
	var s DeleteClusterResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DeleteCluster(options ...string) (*DeleteClusterResp, error) {
	return DefaultClient.DeleteCluster(options...)
}

func (r *DeleteClusterResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
