// 2018-01-03 16:17:16.489101 -0800 PST m=+378.397225109
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ccs

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DeleteClusterInstancesResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		RequestID int64 `json:"requestId"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/457/9446
func (c *CcsClient) DeleteClusterInstances(options ...string) (*DeleteClusterInstancesResp, error) {
	resp, err := c.DoAction("DeleteClusterInstances", options...)
	if err != nil {
		return nil, err
	}
	var s DeleteClusterInstancesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DeleteClusterInstances(options ...string) (*DeleteClusterInstancesResp, error) {
	return DefaultClient.DeleteClusterInstances(options...)
}

func (r *DeleteClusterInstancesResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
