// 2017-11-09 10:50:32.303054696 +0800 CST m=+0.792937342
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ccs

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeClusterServiceResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		Services   []interface{} `json:"services"`
		TotalCount int64         `json:"totalCount"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/457/9440
func DescribeClusterService(options ...string) (*DescribeClusterServiceResp, error) {
	resp, err := DoAction("DescribeClusterService", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeClusterServiceResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeClusterServiceResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
