// 2018-01-06 16:09:31.406067 -0800 PST m=+349.704620012
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ccs

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeServiceInstanceResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		Instances []struct {
			Containers   interface{} `json:"containers"`
			CreatedAt    string      `json:"createdAt"`
			IP           string      `json:"ip"`
			Name         string      `json:"name"`
			NodeIP       string      `json:"nodeIp"`
			NodeName     string      `json:"nodeName"`
			ReadyCount   int64       `json:"readyCount"`
			Reason       string      `json:"reason"`
			RestartCount int64       `json:"restartCount"`
			SrcReason    string      `json:"srcReason"`
			Status       string      `json:"status"`
		} `json:"instances"`
		TotalCount int64 `json:"totalCount"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/457/9433
func (c *CcsClient) DescribeServiceInstance(options ...string) (*DescribeServiceInstanceResp, error) {
	resp, err := c.DoAction("DescribeServiceInstance", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeServiceInstanceResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeServiceInstance(options ...string) (*DescribeServiceInstanceResp, error) {
	return DefaultClient.DescribeServiceInstance(options...)
}

func (r *DescribeServiceInstanceResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
