// 2018-01-06 16:09:17.980939 -0800 PST m=+336.279451487
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ccs

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeServiceEventResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		EventList []struct {
			Count     int64  `json:"count"`
			FirstSeen string `json:"firstSeen"`
			LastSeen  string `json:"lastSeen"`
			Level     string `json:"level"`
			Message   string `json:"message"`
			ObjName   string `json:"objName"`
			ObjType   string `json:"objType"`
			Reason    string `json:"reason"`
			SrcReason string `json:"srcReason"`
		} `json:"eventList"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/457/9443
func (c *CcsClient) DescribeServiceEvent(options ...string) (*DescribeServiceEventResp, error) {
	resp, err := c.DoAction("DescribeServiceEvent", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeServiceEventResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeServiceEvent(options ...string) (*DescribeServiceEventResp, error) {
	return DefaultClient.DescribeServiceEvent(options...)
}

func (r *DescribeServiceEventResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
