// 2017-11-12 18:46:46.528914 +0800 CST m=+10.685820343
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ccs

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ModifyClusterServiceResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/457/9434
func ModifyClusterService(options ...string) (*ModifyClusterServiceResp, error) {
	resp, err := DoAction("ModifyClusterService", options...)
	if err != nil {
		return nil, err
	}
	var s ModifyClusterServiceResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *ModifyClusterServiceResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
