// 2018-01-06 16:09:04.649379 -0800 PST m=+322.947852629
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package ccs

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ResumeClusterServiceResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/457/9442
func (c *CcsClient) ResumeClusterService(options ...string) (*ResumeClusterServiceResp, error) {
	resp, err := c.DoAction("ResumeClusterService", options...)
	if err != nil {
		return nil, err
	}
	var s ResumeClusterServiceResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func ResumeClusterService(options ...string) (*ResumeClusterServiceResp, error) {
	return DefaultClient.ResumeClusterService(options...)
}

func (r *ResumeClusterServiceResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
