// 2018-02-06 16:33:31.874101 -0800 PST m=+23.982820245
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cmq

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type BatchDeleteMessageResp struct {
	ClientRequestID int64  `json:"clientRequestId"`
	Code            int64  `json:"code"`
	Message         string `json:"message"`
	RequestID       string `json:"requestId"`
}

// Implement https://cloud.tencent.com/document/api/406/5841
func (c *CmqClient) BatchDeleteMessage(options ...string) (*BatchDeleteMessageResp, error) {
	resp, err := c.DoAction("BatchDeleteMessage", options...)
	if err != nil {
		return nil, err
	}
	var s BatchDeleteMessageResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func BatchDeleteMessage(options ...string) (*BatchDeleteMessageResp, error) {
	return DefaultClient.BatchDeleteMessage(options...)
}

func (r *BatchDeleteMessageResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
