// 2018-02-08 13:05:38.583712 -0800 PST m=+12.047132937
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cmq

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type BatchSendMessageResp struct {
	ClientRequestID float64 `json:"clientRequestId"`
	Code            float64 `json:"code"`
	Message         string  `json:"message"`
	MsgList         []struct {
		MsgID string `json:"msgId"`
	} `json:"msgList"`
	RequestID string `json:"requestId"`
}

// Implement https://cloud.tencent.com/document/api/406/5838
func (c *CmqClient) BatchSendMessage(options ...string) (*BatchSendMessageResp, error) {
	resp, err := c.DoAction("BatchSendMessage", options...)
	if err != nil {
		return nil, err
	}
	var s BatchSendMessageResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func BatchSendMessage(options ...string) (*BatchSendMessageResp, error) {
	return DefaultClient.BatchSendMessage(options...)
}

func (r *BatchSendMessageResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
