// 2018-02-08 13:05:51.957089 -0800 PST m=+25.420346660
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cmq

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type CreateTopicResp struct {
	Code      float64 `json:"code"`
	Message   string  `json:"message"`
	RequestID string  `json:"requestId"`
	TopicID   string  `json:"topicId"`
}

// Implement https://cloud.tencent.com/document/api/406/7405
func (c *CmqClient) CreateTopic(options ...string) (*CreateTopicResp, error) {
	resp, err := c.DoAction("CreateTopic", options...)
	if err != nil {
		return nil, err
	}
	var s CreateTopicResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func CreateTopic(options ...string) (*CreateTopicResp, error) {
	return DefaultClient.CreateTopic(options...)
}

func (r *CreateTopicResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
