// 2017-10-04 18:44:30.876706305 -0700 PDT
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at

package cmq
import (
	"encoding/json"
)


type DeleteQueueResp struct {
	Code      int64  `json:"code"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
}


// Implement https://cloud.tencent.com/document/api/406/5836
func DeleteQueue(options ...string) (*DeleteQueueResp, error) {
	resp, err := DoAction("DeleteQueue", options...)
	if err != nil {
		return nil, err
	}
	var s DeleteQueueResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}
