// 2018-02-08 13:05:38.14294 -0800 PST m=+11.606366814
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cmq

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DeleteMessageResp struct {
	ClientRequestID float64 `json:"clientRequestId"`
	Code            float64 `json:"code"`
	Message         string  `json:"message"`
	RequestID       string  `json:"requestId"`
}

// Implement https://cloud.tencent.com/document/api/406/5840
func (c *CmqClient) DeleteMessage(options ...string) (*DeleteMessageResp, error) {
	resp, err := c.DoAction("DeleteMessage", options...)
	if err != nil {
		return nil, err
	}
	var s DeleteMessageResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DeleteMessage(options ...string) (*DeleteMessageResp, error) {
	return DefaultClient.DeleteMessage(options...)
}

func (r *DeleteMessageResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
