// +build ignore

package main

import (
	. "."
	"bytes"
	"fmt"
	"github.com/ChimeraCoder/gojson"
	"io/ioutil"
	"log"
	"strings"
	"text/template"
	"time"
)

var (
	docRoot   = "https://cloud.tencent.com/document/api/"
	queryName = fmt.Sprintf("query%d", time.Now().Unix())
	seq       = []string{
		"CreateQueue",
		"ListQueue",
		"DeleteQueue",
	}
	funcMap = map[string][]string{
		"CreateQueue": []string{"431/5832", "queueName=" + queryName},
		"ListQueue":   []string{"406/5833"},
		"DeleteQueue": []string{"406/5836", "queueName=" + queryName},
	}
	pkgName = "cmq"
)

func main() {
	for _, action := range seq {
		query := funcMap[action][1:]
		document := fmt.Sprintf("%s%s", docRoot, funcMap[action][0])
		fmt.Println("start generate", action)
		b, err := DoAction(action, query...)
		if err != nil {
			log.Println(action, err.Error())
			continue
		}
		str := fmt.Sprintf("%sResp", action)
		res, err := gojson.Generate(bytes.NewBuffer(b), gojson.ParseJson, str, pkgName, []string{"json"}, false)
		if err != nil {
			log.Println(action, err.Error())
			continue
		}
		s := strings.Join(strings.Split(string(res), "\n")[1:], "\n")

		var buf bytes.Buffer
		packageTemplate.Execute(&buf, struct {
			Timestamp time.Time
			PkgName   string
			Action    string
			Struct    string
			Document  string
		}{
			Timestamp: time.Now(),
			PkgName:   pkgName,
			Action:    action,
			Struct:    s,
			Document:  document,
		})
		var overwrite bool
		fname := action + ".go"
		current, err := ioutil.ReadFile(fname)
		if err != nil {
			overwrite = true
		}
		currentS := strings.Join(strings.Split(string(current), "\n")[1:], "\n")
		bufS := strings.Join(strings.Split(buf.String(), "\n")[1:], "\n")
		if !overwrite && currentS != bufS {
			overwrite = true
		}
		if overwrite {
			err = ioutil.WriteFile(fname, buf.Bytes(), 0644)
			if err != nil {
				log.Println(action, err.Error())
				continue
			}
			fmt.Println("finish generate", action)
		} else {
			fmt.Println("finish nochange", action)
		}
	}
}

var packageTemplate = template.Must(template.New("").Parse(`// {{ .Timestamp }}
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at

package {{.PkgName}}
import (
	"encoding/json"
)

{{.Struct}}

// Implement {{.Document}}
func {{.Action}}(options ...string) (*{{.Action}}Resp, error) {
	resp, err := DoAction("{{.Action}}", options...)
	if err != nil {
		return nil, err
	}
	var s {{.Action}}Resp
	err = json.Unmarshal(resp, &s)
	return &s, err
}
`))
