// 2018-02-08 13:05:28.135679 -0800 PST m=+1.599227696
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cmq

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type GetQueueAttributesResp struct {
	ActiveMsgNum        float64 `json:"activeMsgNum"`
	ClientRequestID     float64 `json:"clientRequestId"`
	Code                float64 `json:"code"`
	CreateTime          float64 `json:"createTime"`
	DelayMsgNum         float64 `json:"delayMsgNum"`
	InactiveMsgNum      float64 `json:"inactiveMsgNum"`
	LastModifyTime      float64 `json:"lastModifyTime"`
	MaxMsgHeapNum       float64 `json:"maxMsgHeapNum"`
	MaxMsgSize          float64 `json:"maxMsgSize"`
	Message             string  `json:"message"`
	MinMsgTime          float64 `json:"minMsgTime"`
	MsgRetentionSeconds float64 `json:"msgRetentionSeconds"`
	PollingWaitSeconds  float64 `json:"pollingWaitSeconds"`
	RequestID           string  `json:"requestId"`
	RewindMsgNum        float64 `json:"rewindMsgNum"`
	RewindSeconds       float64 `json:"rewindSeconds"`
	VisibilityTimeout   float64 `json:"visibilityTimeout"`
}

// Implement https://cloud.tencent.com/document/api/406/5834
func (c *CmqClient) GetQueueAttributes(options ...string) (*GetQueueAttributesResp, error) {
	resp, err := c.DoAction("GetQueueAttributes", options...)
	if err != nil {
		return nil, err
	}
	var s GetQueueAttributesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func GetQueueAttributes(options ...string) (*GetQueueAttributesResp, error) {
	return DefaultClient.GetQueueAttributes(options...)
}

func (r *GetQueueAttributesResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
