// 2018-02-06 11:33:05.861687 -0800 PST m=+2.097523986
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cmq

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type GetQueueAttributesResp struct {
	ActiveMsgNum        int64  `json:"activeMsgNum"`
	ClientRequestID     int64  `json:"clientRequestId"`
	Code                int64  `json:"code"`
	CreateTime          int64  `json:"createTime"`
	DelayMsgNum         int64  `json:"delayMsgNum"`
	InactiveMsgNum      int64  `json:"inactiveMsgNum"`
	LastModifyTime      int64  `json:"lastModifyTime"`
	MaxMsgHeapNum       int64  `json:"maxMsgHeapNum"`
	MaxMsgSize          int64  `json:"maxMsgSize"`
	Message             string `json:"message"`
	MinMsgTime          int64  `json:"minMsgTime"`
	MsgRetentionSeconds int64  `json:"msgRetentionSeconds"`
	PollingWaitSeconds  int64  `json:"pollingWaitSeconds"`
	RequestID           string `json:"requestId"`
	RewindMsgNum        int64  `json:"rewindMsgNum"`
	RewindSeconds       int64  `json:"rewindSeconds"`
	VisibilityTimeout   int64  `json:"visibilityTimeout"`
}

// Implement https://cloud.tencent.com/document/api/406/5834
func (c *CmqClient) GetQueueAttributes(options ...string) (*GetQueueAttributesResp, error) {
	resp, err := c.DoAction("GetQueueAttributes", options...)
	if err != nil {
		return nil, err
	}
	var s GetQueueAttributesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func GetQueueAttributes(options ...string) (*GetQueueAttributesResp, error) {
	return DefaultClient.GetQueueAttributes(options...)
}

func (r *GetQueueAttributesResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
