// 2018-02-06 18:00:05.471326 -0800 PST m=+29.590506724
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cmq

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type GetSubscriptionAttributesResp struct {
	BindingKey          []interface{} `json:"bindingKey"`
	Code                int64         `json:"code"`
	CreateTime          int64         `json:"createTime"`
	Endpoint            string        `json:"endpoint"`
	FilterTags          []interface{} `json:"filterTags"`
	LastModifyTime      int64         `json:"lastModifyTime"`
	Message             string        `json:"message"`
	MsgCount            int64         `json:"msgCount"`
	NotifyContentFormat string        `json:"notifyContentFormat"`
	NotifyStrategy      string        `json:"notifyStrategy"`
	Protocol            string        `json:"protocol"`
	RequestID           string        `json:"requestId"`
	TopicOwner          string        `json:"topicOwner"`
}

// Implement https://cloud.tencent.com/document/api/406/7418
func (c *CmqClient) GetSubscriptionAttributes(options ...string) (*GetSubscriptionAttributesResp, error) {
	resp, err := c.DoAction("GetSubscriptionAttributes", options...)
	if err != nil {
		return nil, err
	}
	var s GetSubscriptionAttributesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func GetSubscriptionAttributes(options ...string) (*GetSubscriptionAttributesResp, error) {
	return DefaultClient.GetSubscriptionAttributes(options...)
}

func (r *GetSubscriptionAttributesResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
