// 2018-02-08 13:05:53.002445 -0800 PST m=+26.465689708
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cmq

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type GetTopicAttributesResp struct {
	Code                float64 `json:"code"`
	CreateTime          float64 `json:"createTime"`
	FilterType          float64 `json:"filterType"`
	LastModifyTime      float64 `json:"lastModifyTime"`
	MaxMsgSize          float64 `json:"maxMsgSize"`
	Message             string  `json:"message"`
	MsgCount            float64 `json:"msgCount"`
	MsgRetentionSeconds float64 `json:"msgRetentionSeconds"`
	RequestID           string  `json:"requestId"`
	TopicID             string  `json:"topicId"`
	TopicName           string  `json:"topicName"`
}

// Implement https://cloud.tencent.com/document/api/406/7408
func (c *CmqClient) GetTopicAttributes(options ...string) (*GetTopicAttributesResp, error) {
	resp, err := c.DoAction("GetTopicAttributes", options...)
	if err != nil {
		return nil, err
	}
	var s GetTopicAttributesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func GetTopicAttributes(options ...string) (*GetTopicAttributesResp, error) {
	return DefaultClient.GetTopicAttributes(options...)
}

func (r *GetTopicAttributesResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
