// 2017-11-06 07:13:20.107849512 +0000 UTC m=+10.485171588
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cmq

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ListQueueResp struct {
	Code      int64  `json:"code"`
	Message   string `json:"message"`
	QueueList []struct {
		QueueID   string `json:"queueId"`
		QueueName string `json:"queueName"`
	} `json:"queueList"`
	RequestID  string `json:"requestId"`
	TotalCount int64  `json:"totalCount"`
}

// Implement https://cloud.tencent.com/document/api/406/5833
func ListQueue(options ...string) (*ListQueueResp, error) {
	resp, err := DoAction("ListQueue", options...)
	if err != nil {
		return nil, err
	}
	var s ListQueueResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *ListQueueResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
