// 2018-02-06 18:00:04.895433 -0800 PST m=+29.014613016
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cmq

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ListSubscriptionByTopicResp struct {
	Code             int64  `json:"code"`
	Message          string `json:"message"`
	RequestID        string `json:"requestId"`
	SubscriptionList []struct {
		Endpoint         string `json:"endpoint"`
		Protocol         string `json:"protocol"`
		SubscriptionID   string `json:"subscriptionId"`
		SubscriptionName string `json:"subscriptionName"`
	} `json:"subscriptionList"`
	TotalCount int64 `json:"totalCount"`
}

// Implement https://cloud.tencent.com/document/api/406/7415
func (c *CmqClient) ListSubscriptionByTopic(options ...string) (*ListSubscriptionByTopicResp, error) {
	resp, err := c.DoAction("ListSubscriptionByTopic", options...)
	if err != nil {
		return nil, err
	}
	var s ListSubscriptionByTopicResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func ListSubscriptionByTopic(options ...string) (*ListSubscriptionByTopicResp, error) {
	return DefaultClient.ListSubscriptionByTopic(options...)
}

func (r *ListSubscriptionByTopicResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
