// 2018-02-08 13:05:27.654312 -0800 PST m=+1.117865872
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cmq

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ListQueueResp struct {
	ClientRequestID float64 `json:"clientRequestId"`
	Code            float64 `json:"code"`
	Message         string  `json:"message"`
	QueueList       []struct {
		QueueID   string `json:"queueId"`
		QueueName string `json:"queueName"`
	} `json:"queueList"`
	RequestID  string  `json:"requestId"`
	TotalCount float64 `json:"totalCount"`
}

// Implement https://cloud.tencent.com/document/api/406/5833
func (c *CmqClient) ListQueue(options ...string) (*ListQueueResp, error) {
	resp, err := c.DoAction("ListQueue", options...)
	if err != nil {
		return nil, err
	}
	var s ListQueueResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func ListQueue(options ...string) (*ListQueueResp, error) {
	return DefaultClient.ListQueue(options...)
}

func (r *ListQueueResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
