// 2018-02-08 13:05:32.506558 -0800 PST m=+5.970053108
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cmq

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ReceiveMessageResp struct {
	ClientRequestID      float64 `json:"clientRequestId"`
	Code                 float64 `json:"code"`
	DequeueCount         float64 `json:"dequeueCount"`
	EnqueueTime          float64 `json:"enqueueTime"`
	FirstDequeueTime     float64 `json:"firstDequeueTime"`
	Message              string  `json:"message"`
	MsgBody              string  `json:"msgBody"`
	MsgID                string  `json:"msgId"`
	NextVisibleTime      float64 `json:"nextVisibleTime"`
	OriginalDeQueueCount float64 `json:"originalDeQueueCount"`
	OriginalEnQueueTime  float64 `json:"originalEnQueueTime"`
	OriginalQueueID      string  `json:"originalQueueId"`
	ReceiptHandle        string  `json:"receiptHandle"`
	RequestID            string  `json:"requestId"`
}

// Implement https://cloud.tencent.com/document/api/406/5839
func (c *CmqClient) ReceiveMessage(options ...string) (*ReceiveMessageResp, error) {
	resp, err := c.DoAction("ReceiveMessage", options...)
	if err != nil {
		return nil, err
	}
	var s ReceiveMessageResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func ReceiveMessage(options ...string) (*ReceiveMessageResp, error) {
	return DefaultClient.ReceiveMessage(options...)
}

func (r *ReceiveMessageResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
