// 2018-02-08 13:05:29.076876 -0800 PST m=+2.540412732
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cmq

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type SendMessageResp struct {
	ClientRequestID float64 `json:"clientRequestId"`
	Code            float64 `json:"code"`
	Message         string  `json:"message"`
	MsgID           string  `json:"msgId"`
	RequestID       string  `json:"requestId"`
}

// Implement https://cloud.tencent.com/document/api/406/5837
func (c *CmqClient) SendMessage(options ...string) (*SendMessageResp, error) {
	resp, err := c.DoAction("SendMessage", options...)
	if err != nil {
		return nil, err
	}
	var s SendMessageResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func SendMessage(options ...string) (*SendMessageResp, error) {
	return DefaultClient.SendMessage(options...)
}

func (r *SendMessageResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
