// 2018-02-08 13:05:57.099453 -0800 PST m=+30.562648226
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package cmq

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type UnsubscribeResp struct {
	Code      float64 `json:"code"`
	Message   string  `json:"message"`
	RequestID string  `json:"requestId"`
}

// Implement https://cloud.tencent.com/document/api/406/7417
func (c *CmqClient) Unsubscribe(options ...string) (*UnsubscribeResp, error) {
	resp, err := c.DoAction("Unsubscribe", options...)
	if err != nil {
		return nil, err
	}
	var s UnsubscribeResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func Unsubscribe(options ...string) (*UnsubscribeResp, error) {
	return DefaultClient.Unsubscribe(options...)
}

func (r *UnsubscribeResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
