// 2018-01-10 10:13:15.084799 -0800 PST m=+19.264356483
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package lb

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type CreateLoadBalancerListenersResp struct {
	Code        int64    `json:"code"`
	CodeDesc    string   `json:"codeDesc"`
	ListenerIds []string `json:"listenerIds"`
	Message     string   `json:"message"`
	RequestID   int64    `json:"requestId"`
}

// Implement https://cloud.tencent.com/document/api/214/1255
func (c *LbClient) CreateLoadBalancerListeners(options ...string) (*CreateLoadBalancerListenersResp, error) {
	resp, err := c.DoAction("CreateLoadBalancerListeners", options...)
	if err != nil {
		return nil, err
	}
	var s CreateLoadBalancerListenersResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func CreateLoadBalancerListeners(options ...string) (*CreateLoadBalancerListenersResp, error) {
	return DefaultClient.CreateLoadBalancerListeners(options...)
}

func (r *CreateLoadBalancerListenersResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
