// 2018-01-10 10:13:08.074995 -0800 PST m=+12.254551657
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package lb

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type CreateLoadBalancerResp struct {
	Code              int64    `json:"code"`
	CodeDesc          string   `json:"codeDesc"`
	DealIds           []string `json:"dealIds"`
	Message           string   `json:"message"`
	RequestID         int64    `json:"requestId"`
	UnLoadBalancerIds struct {
		One3951909 []string `json:"13951909"`
	} `json:"unLoadBalancerIds"`
}

// Implement https://cloud.tencent.com/document/api/214/1254
func (c *LbClient) CreateLoadBalancer(options ...string) (*CreateLoadBalancerResp, error) {
	resp, err := c.DoAction("CreateLoadBalancer", options...)
	if err != nil {
		return nil, err
	}
	var s CreateLoadBalancerResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func CreateLoadBalancer(options ...string) (*CreateLoadBalancerResp, error) {
	return DefaultClient.CreateLoadBalancer(options...)
}

func (r *CreateLoadBalancerResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
