// 2017-12-11 16:27:27.668338 -0800 PST m=+15.515698808
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package lb

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DeregisterInstancesFromLoadBalancerResp struct {
	Code      int64  `json:"code"`
	CodeDesc  string `json:"codeDesc"`
	Message   string `json:"message"`
	RequestID int64  `json:"requestId"`
}

// Implement https://cloud.tencent.com/document/api/214/1258
func DeregisterInstancesFromLoadBalancer(options ...string) (*DeregisterInstancesFromLoadBalancerResp, error) {
	resp, err := DoAction("DeregisterInstancesFromLoadBalancer", options...)
	if err != nil {
		return nil, err
	}
	var s DeregisterInstancesFromLoadBalancerResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DeregisterInstancesFromLoadBalancerResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
