// 2017-12-11 16:32:34.5157 -0800 PST m=+14.975629964
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package lb

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeLoadBalancerBackendsResp struct {
	BackendSet []struct {
		InstanceID     string   `json:"instanceId"`
		InstanceName   string   `json:"instanceName"`
		InstanceStatus int64    `json:"instanceStatus"`
		LanIP          string   `json:"lanIp"`
		UnInstanceID   string   `json:"unInstanceId"`
		WanIPSet       []string `json:"wanIpSet"`
		Weight         int64    `json:"weight"`
	} `json:"backendSet"`
	Code       int64         `json:"code"`
	CodeDesc   string        `json:"codeDesc"`
	Data       []interface{} `json:"data"`
	Message    string        `json:"message"`
	TotalCount int64         `json:"totalCount"`
}

// Implement https://cloud.tencent.com/document/api/214/1259
func DescribeLoadBalancerBackends(options ...string) (*DescribeLoadBalancerBackendsResp, error) {
	resp, err := DoAction("DescribeLoadBalancerBackends", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeLoadBalancerBackendsResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeLoadBalancerBackendsResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
