// 2018-02-08 13:10:36.14437 -0800 PST m=+24.496553347
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package lb

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeLoadBalancerListenersResp struct {
	Code        float64 `json:"code"`
	CodeDesc    string  `json:"codeDesc"`
	ListenerSet []struct {
		SSLMode          string  `json:"SSLMode"`
		CertCaID         string  `json:"certCaId"`
		CertID           string  `json:"certId"`
		HealthNum        float64 `json:"healthNum"`
		HealthSwitch     float64 `json:"healthSwitch"`
		HTTPCheckPath    string  `json:"httpCheckPath"`
		HTTPCode         float64 `json:"httpCode"`
		HTTPHash         string  `json:"httpHash"`
		InstancePort     float64 `json:"instancePort"`
		IntervalTime     float64 `json:"intervalTime"`
		ListenerID       string  `json:"listenerId"`
		ListenerName     string  `json:"listenerName"`
		LoadBalancerPort float64 `json:"loadBalancerPort"`
		Protocol         float64 `json:"protocol"`
		Scheduler        string  `json:"scheduler"`
		SessionExpire    float64 `json:"sessionExpire"`
		Status           float64 `json:"status"`
		TimeOut          float64 `json:"timeOut"`
		UnListenerID     string  `json:"unListenerId"`
		UnhealthNum      float64 `json:"unhealthNum"`
	} `json:"listenerSet"`
	Message    string  `json:"message"`
	TotalCount float64 `json:"totalCount"`
}

// Implement https://cloud.tencent.com/document/api/214/1260
func (c *LbClient) DescribeLoadBalancerListeners(options ...string) (*DescribeLoadBalancerListenersResp, error) {
	resp, err := c.DoAction("DescribeLoadBalancerListeners", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeLoadBalancerListenersResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeLoadBalancerListeners(options ...string) (*DescribeLoadBalancerListenersResp, error) {
	return DefaultClient.DescribeLoadBalancerListeners(options...)
}

func (r *DescribeLoadBalancerListenersResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
