// 2018-01-10 10:13:37.18749 -0800 PST m=+41.367051734
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package lb

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeLBHealthStatusResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     []struct {
		HealthStatus int64  `json:"healthStatus"`
		IP           string `json:"ip"`
		Port         int64  `json:"port"`
		Protocol     string `json:"protocol"`
		Vport        int64  `json:"vport"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/214/1326
func (c *LbClient) DescribeLBHealthStatus(options ...string) (*DescribeLBHealthStatusResp, error) {
	resp, err := c.DoAction("DescribeLBHealthStatus", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeLBHealthStatusResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeLBHealthStatus(options ...string) (*DescribeLBHealthStatusResp, error) {
	return DefaultClient.DescribeLBHealthStatus(options...)
}

func (r *DescribeLBHealthStatusResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
