// 2018-02-08 13:10:48.490415 -0800 PST m=+36.842476948
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package lb

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeLoadBalancerBackendsResp struct {
	BackendSet []interface{} `json:"backendSet"`
	Code       float64       `json:"code"`
	CodeDesc   string        `json:"codeDesc"`
	Data       []interface{} `json:"data"`
	Message    string        `json:"message"`
	TotalCount float64       `json:"totalCount"`
}

// Implement https://cloud.tencent.com/document/api/214/1259
func (c *LbClient) DescribeLoadBalancerBackends(options ...string) (*DescribeLoadBalancerBackendsResp, error) {
	resp, err := c.DoAction("DescribeLoadBalancerBackends", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeLoadBalancerBackendsResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeLoadBalancerBackends(options ...string) (*DescribeLoadBalancerBackendsResp, error) {
	return DefaultClient.DescribeLoadBalancerBackends(options...)
}

func (r *DescribeLoadBalancerBackendsResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
