// 2018-02-08 13:10:24.565532 -0800 PST m=+12.917829178
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package lb

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeLoadBalancersResp struct {
	Code            float64 `json:"code"`
	CodeDesc        string  `json:"codeDesc"`
	LoadBalancerSet []struct {
		CreateTime         string  `json:"createTime"`
		Domain             string  `json:"domain"`
		ExpireTime         string  `json:"expireTime"`
		Forward            float64 `json:"forward"`
		InternetAccessible struct {
			InternetChargeType      string  `json:"internetChargeType"`
			InternetMaxBandwidthOut float64 `json:"internetMaxBandwidthOut"`
		} `json:"internetAccessible"`
		IsolatedTime    string  `json:"isolatedTime"`
		Isolation       float64 `json:"isolation"`
		LbChargePrepaid struct {
			Period    float64 `json:"period"`
			RenewFlag string  `json:"renewFlag"`
		} `json:"lbChargePrepaid"`
		LbChargeType     string   `json:"lbChargeType"`
		LoadBalancerID   string   `json:"loadBalancerId"`
		LoadBalancerName string   `json:"loadBalancerName"`
		LoadBalancerType float64  `json:"loadBalancerType"`
		LoadBalancerVips []string `json:"loadBalancerVips"`
		Log              string   `json:"log"`
		OpenBgp          float64  `json:"openBgp"`
		ProjectID        float64  `json:"projectId"`
		RsRegionInfo     struct {
			Region string `json:"region"`
			VpcID  string `json:"vpcId"`
		} `json:"rsRegionInfo"`
		Snat             bool    `json:"snat"`
		Status           float64 `json:"status"`
		StatusTime       string  `json:"statusTime"`
		SubnetID         float64 `json:"subnetId"`
		UnLoadBalancerID string  `json:"unLoadBalancerId"`
		UniqVpcID        string  `json:"uniqVpcId"`
		VpcID            float64 `json:"vpcId"`
	} `json:"loadBalancerSet"`
	Message    string  `json:"message"`
	TotalCount float64 `json:"totalCount"`
}

// Implement https://cloud.tencent.com/document/api/214/1261
func (c *LbClient) DescribeLoadBalancers(options ...string) (*DescribeLoadBalancersResp, error) {
	resp, err := c.DoAction("DescribeLoadBalancers", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeLoadBalancersResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeLoadBalancers(options ...string) (*DescribeLoadBalancersResp, error) {
	return DefaultClient.DescribeLoadBalancers(options...)
}

func (r *DescribeLoadBalancersResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
