// 2018-01-10 09:12:45.850826 -0800 PST m=+8.333416236
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package lb

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type InquiryLBPriceResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
	Price    int64  `json:"price"`
}

// Implement https://cloud.tencent.com/document/api/214/1328
func (c *LbClient) InquiryLBPrice(options ...string) (*InquiryLBPriceResp, error) {
	resp, err := c.DoAction("InquiryLBPrice", options...)
	if err != nil {
		return nil, err
	}
	var s InquiryLBPriceResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func InquiryLBPrice(options ...string) (*InquiryLBPriceResp, error) {
	return DefaultClient.InquiryLBPrice(options...)
}

func (r *InquiryLBPriceResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
