// 2018-01-09 09:22:56.193873 -0800 PST m=+57.519644159
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type AddUserGwResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
	UserGwID string `json:"userGwId"`
}

// Implement https://cloud.tencent.com/document/api/215/5116
func (c *VpcClient) AddUserGw(options ...string) (*AddUserGwResp, error) {
	resp, err := c.DoAction("AddUserGw", options...)
	if err != nil {
		return nil, err
	}
	var s AddUserGwResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func AddUserGw(options ...string) (*AddUserGwResp, error) {
	return DefaultClient.AddUserGw(options...)
}

func (r *AddUserGwResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
