// 2018-01-09 09:22:36.645596 -0800 PST m=+37.971331075
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type AssociateRouteTableResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/215/1416
func (c *VpcClient) AssociateRouteTable(options ...string) (*AssociateRouteTableResp, error) {
	resp, err := c.DoAction("AssociateRouteTable", options...)
	if err != nil {
		return nil, err
	}
	var s AssociateRouteTableResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func AssociateRouteTable(options ...string) (*AssociateRouteTableResp, error) {
	return DefaultClient.AssociateRouteTable(options...)
}

func (r *AssociateRouteTableResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
