// 2017-11-17 02:57:07.97847 -0800 PST m=+24.666056874
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type CreateRouteTableResp struct {
	Code          int64  `json:"code"`
	CodeDesc      string `json:"codeDesc"`
	Message       string `json:"message"`
	RouteTableID  string `json:"routeTableId"`
	RouteTableSet []struct {
		Description          interface{} `json:"description"`
		DestinationCidrBlock string      `json:"destinationCidrBlock"`
		NextHub              string      `json:"nextHub"`
		NextType             int64       `json:"nextType"`
	} `json:"routeTableSet"`
	UnRouteTableID string `json:"unRouteTableId"`
}

// Implement https://cloud.tencent.com/document/api/215/1419
func CreateRouteTable(options ...string) (*CreateRouteTableResp, error) {
	resp, err := DoAction("CreateRouteTable", options...)
	if err != nil {
		return nil, err
	}
	var s CreateRouteTableResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *CreateRouteTableResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
