// 2018-01-09 09:23:09.968933 -0800 PST m=+71.294730172
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type CreateLocalIPTranslationNatRuleResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		TaskID int64 `json:"taskId"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/215/5185
func (c *VpcClient) CreateLocalIPTranslationNatRule(options ...string) (*CreateLocalIPTranslationNatRuleResp, error) {
	resp, err := c.DoAction("CreateLocalIPTranslationNatRule", options...)
	if err != nil {
		return nil, err
	}
	var s CreateLocalIPTranslationNatRuleResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func CreateLocalIPTranslationNatRule(options ...string) (*CreateLocalIPTranslationNatRuleResp, error) {
	return DefaultClient.CreateLocalIPTranslationNatRule(options...)
}

func (r *CreateLocalIPTranslationNatRuleResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
