// 2018-01-09 09:22:23.881548 -0800 PST m=+25.207259281
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type CreateVpcPeeringConnectionResp struct {
	Code                int64  `json:"code"`
	CodeDesc            string `json:"codeDesc"`
	Message             string `json:"message"`
	PeeringConnectionID string `json:"peeringConnectionId"`
}

// Implement https://cloud.tencent.com/document/api/215/2107
func (c *VpcClient) CreateVpcPeeringConnection(options ...string) (*CreateVpcPeeringConnectionResp, error) {
	resp, err := c.DoAction("CreateVpcPeeringConnection", options...)
	if err != nil {
		return nil, err
	}
	var s CreateVpcPeeringConnectionResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func CreateVpcPeeringConnection(options ...string) (*CreateVpcPeeringConnectionResp, error) {
	return DefaultClient.CreateVpcPeeringConnection(options...)
}

func (r *CreateVpcPeeringConnectionResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
