// 2017-11-17 12:57:54.868306 -0800 PST m=+28.564581513
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type CreateNetworkAclResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		NetworkAclID string `json:"networkAclId"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/215/1437
func CreateNetworkAcl(options ...string) (*CreateNetworkAclResp, error) {
	resp, err := DoAction("CreateNetworkAcl", options...)
	if err != nil {
		return nil, err
	}
	var s CreateNetworkAclResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *CreateNetworkAclResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
