// 2017-11-27 23:26:09.194866 -0800 PST m=+176.301817876
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type CreateDirectConnectGatewayResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		DirectConnectGatewayID string `json:"directConnectGatewayId"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/215/4824
func CreateDirectConnectGateway(options ...string) (*CreateDirectConnectGatewayResp, error) {
	resp, err := DoAction("CreateDirectConnectGateway", options...)
	if err != nil {
		return nil, err
	}
	var s CreateDirectConnectGatewayResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *CreateDirectConnectGatewayResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
