// 2017-11-14 16:59:15.094243 -0800 PST m=+6.639263598
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type CreateSubnetResp struct {
	Code      int64  `json:"code"`
	CodeDesc  string `json:"codeDesc"`
	Message   string `json:"message"`
	SubnetSet []struct {
		CidrBlock    string `json:"cidrBlock"`
		RouteTableID string `json:"routeTableId"`
		SubnetID     string `json:"subnetId"`
		SubnetName   string `json:"subnetName"`
		UnSubnetID   string `json:"unSubnetId"`
		Zone         string `json:"zone"`
		ZoneID       int64  `json:"zoneId"`
	} `json:"subnetSet"`
}

// Implement https://cloud.tencent.com/document/api/215/1314
func CreateSubnet(options ...string) (*CreateSubnetResp, error) {
	resp, err := DoAction("CreateSubnet", options...)
	if err != nil {
		return nil, err
	}
	var s CreateSubnetResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *CreateSubnetResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
