// 2018-01-09 09:23:37.908807 -0800 PST m=+99.234656030
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DeleteDirectConnectGatewayResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		TaskID int64 `json:"taskId"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/215/4825
func (c *VpcClient) DeleteDirectConnectGateway(options ...string) (*DeleteDirectConnectGatewayResp, error) {
	resp, err := c.DoAction("DeleteDirectConnectGateway", options...)
	if err != nil {
		return nil, err
	}
	var s DeleteDirectConnectGatewayResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DeleteDirectConnectGateway(options ...string) (*DeleteDirectConnectGatewayResp, error) {
	return DefaultClient.DeleteDirectConnectGateway(options...)
}

func (r *DeleteDirectConnectGatewayResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
