// 2017-11-17 02:49:06.884202 -0800 PST m=+24.577705153
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DeleteVpcPeeringConnectionResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/215/2104
func DeleteVpcPeeringConnection(options ...string) (*DeleteVpcPeeringConnectionResp, error) {
	resp, err := DoAction("DeleteVpcPeeringConnection", options...)
	if err != nil {
		return nil, err
	}
	var s DeleteVpcPeeringConnectionResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DeleteVpcPeeringConnectionResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
