// 2018-01-09 09:23:34.88675 -0800 PST m=+96.212593922
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DeleteNatGatewayResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
	TaskID   int64  `json:"taskId"`
}

// Implement https://cloud.tencent.com/document/api/215/4087
func (c *VpcClient) DeleteNatGateway(options ...string) (*DeleteNatGatewayResp, error) {
	resp, err := c.DoAction("DeleteNatGateway", options...)
	if err != nil {
		return nil, err
	}
	var s DeleteNatGatewayResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DeleteNatGateway(options ...string) (*DeleteNatGatewayResp, error) {
	return DefaultClient.DeleteNatGateway(options...)
}

func (r *DeleteNatGatewayResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
