// 2017-11-17 03:54:15.116758 -0800 PST m=+55.520972721
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DeleteRouteTableResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/215/1418
func DeleteRouteTable(options ...string) (*DeleteRouteTableResp, error) {
	resp, err := DoAction("DeleteRouteTable", options...)
	if err != nil {
		return nil, err
	}
	var s DeleteRouteTableResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DeleteRouteTableResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
