// 2017-11-15 11:43:15.764732 -0800 PST m=+21.038980441
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DeleteSubnetResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/215/1312
func DeleteSubnet(options ...string) (*DeleteSubnetResp, error) {
	resp, err := DoAction("DeleteSubnet", options...)
	if err != nil {
		return nil, err
	}
	var s DeleteSubnetResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DeleteSubnetResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
