// 2017-11-17 04:11:30.047334 -0800 PST m=+49.772766659
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DeleteRouteResp struct {
	Code     int64         `json:"code"`
	CodeDesc string        `json:"codeDesc"`
	Data     []interface{} `json:"data"`
	Message  string        `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/215/5689
func DeleteRoute(options ...string) (*DeleteRouteResp, error) {
	resp, err := DoAction("DeleteRoute", options...)
	if err != nil {
		return nil, err
	}
	var s DeleteRouteResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DeleteRouteResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
