// 2017-11-27 23:50:08.539054 -0800 PST m=+100.537335204
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeDirectConnectGatewayResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     []struct {
		CreateTime               string `json:"createTime"`
		DirectConnectGatewayID   string `json:"directConnectGatewayId"`
		DirectConnectGatewayIP   string `json:"directConnectGatewayIp"`
		DirectConnectGatewayName string `json:"directConnectGatewayName"`
		DnaptNum                 int64  `json:"dnaptNum"`
		DnatNum                  int64  `json:"dnatNum"`
		SnaptNum                 int64  `json:"snaptNum"`
		SnatNum                  int64  `json:"snatNum"`
		Type                     int64  `json:"type"`
		UnVpcID                  string `json:"unVpcId"`
		VpcCidrBlock             string `json:"vpcCidrBlock"`
		VpcID                    string `json:"vpcId"`
		VpcName                  string `json:"vpcName"`
	} `json:"data"`
	Message    string `json:"message"`
	TotalCount int64  `json:"totalCount"`
}

// Implement https://cloud.tencent.com/document/api/215/4827
func DescribeDirectConnectGateway(options ...string) (*DescribeDirectConnectGatewayResp, error) {
	resp, err := DoAction("DescribeDirectConnectGateway", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeDirectConnectGatewayResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeDirectConnectGatewayResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
