// 2017-11-15 18:53:19.048748 -0800 PST m=+9.152515333
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeVpcPeeringConnectionsResp struct {
	Code       int64         `json:"code"`
	CodeDesc   string        `json:"codeDesc"`
	Data       []interface{} `json:"data"`
	Message    string        `json:"message"`
	TotalCount int64         `json:"totalCount"`
}

// Implement https://cloud.tencent.com/document/api/215/2101
func DescribeVpcPeeringConnections(options ...string) (*DescribeVpcPeeringConnectionsResp, error) {
	resp, err := DoAction("DescribeVpcPeeringConnections", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeVpcPeeringConnectionsResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeVpcPeeringConnectionsResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
