// 2017-11-27 17:13:58.088129 -0800 PST m=+49.405077006
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeVpnGwResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     []struct {
		Bandwidth        int64  `json:"bandwidth"`
		ChargeType       string `json:"chargeType"`
		CreateTime       string `json:"createTime"`
		DealID           string `json:"dealId"`
		ExpireTime       string `json:"expireTime"`
		HotHaIP          string `json:"hotHaIp"`
		IsAddressBlocked int64  `json:"isAddressBlocked"`
		IsAutoRenewals   bool   `json:"isAutoRenewals"`
		LocalSLAIP       string `json:"localSlaIp"`
		NewPurchasePlan  string `json:"newPurchasePlan"`
		UnVpcID          string `json:"unVpcId"`
		UnVpnGwID        string `json:"unVpnGwId"`
		VpcCidrBlock     string `json:"vpcCidrBlock"`
		VpcID            string `json:"vpcId"`
		VpcName          string `json:"vpcName"`
		VpnGwAddress     string `json:"vpnGwAddress"`
		VpnGwID          int64  `json:"vpnGwId"`
		VpnGwName        string `json:"vpnGwName"`
		VpnGwStatus      int64  `json:"vpnGwStatus"`
	} `json:"data"`
	Message    string `json:"message"`
	TotalCount int64  `json:"totalCount"`
}

// Implement https://cloud.tencent.com/document/api/215/5108
func DescribeVpnGw(options ...string) (*DescribeVpnGwResp, error) {
	resp, err := DoAction("DescribeVpnGw", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeVpnGwResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeVpnGwResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
