// 2017-11-28 17:05:28.335834 -0800 PST m=+290.978207720
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeLocalIPTranslationNatRuleResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		Data []struct {
			Description   string `json:"description"`
			OriginalIP    string `json:"originalIP"`
			TranslationIP string `json:"translationIP"`
		} `json:"data"`
		TotalNum int64 `json:"totalNum"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/215/5188
func DescribeLocalIPTranslationNatRule(options ...string) (*DescribeLocalIPTranslationNatRuleResp, error) {
	resp, err := DoAction("DescribeLocalIPTranslationNatRule", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeLocalIPTranslationNatRuleResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeLocalIPTranslationNatRuleResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
