// 2017-11-28 15:13:15.129602 -0800 PST m=+303.861843177
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeNatGatewayResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     []struct {
		AppID            string        `json:"appId"`
		Bandwidth        int64         `json:"bandwidth"`
		BlockedEipSet    []interface{} `json:"blockedEipSet"`
		CreateTime       string        `json:"createTime"`
		EipCount         int64         `json:"eipCount"`
		EipSet           []string      `json:"eipSet"`
		MaxConcurrent    int64         `json:"maxConcurrent"`
		NatID            string        `json:"natId"`
		NatName          string        `json:"natName"`
		ProductionStatus int64         `json:"productionStatus"`
		State            int64         `json:"state"`
		UnVpcID          string        `json:"unVpcId"`
		VpcID            int64         `json:"vpcId"`
		VpcName          string        `json:"vpcName"`
	} `json:"data"`
	Message    string `json:"message"`
	TotalCount int64  `json:"totalCount"`
}

// Implement https://cloud.tencent.com/document/api/215/4088
func DescribeNatGateway(options ...string) (*DescribeNatGatewayResp, error) {
	resp, err := DoAction("DescribeNatGateway", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeNatGatewayResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeNatGatewayResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
