// 2018-01-09 09:22:57.569204 -0800 PST m=+58.894978373
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeUserGwResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     []struct {
		CreateTime string `json:"createTime"`
		UnUserGwID string `json:"unUserGwId"`
		UserGwAddr string `json:"userGwAddr"`
		UserGwID   int64  `json:"userGwId"`
		UserGwName string `json:"userGwName"`
		VpnConnNum int64  `json:"vpnConnNum"`
	} `json:"data"`
	Message    string `json:"message"`
	TotalCount int64  `json:"totalCount"`
}

// Implement https://cloud.tencent.com/document/api/215/5119
func (c *VpcClient) DescribeUserGw(options ...string) (*DescribeUserGwResp, error) {
	resp, err := c.DoAction("DescribeUserGw", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeUserGwResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeUserGw(options ...string) (*DescribeUserGwResp, error) {
	return DefaultClient.DescribeUserGw(options...)
}

func (r *DescribeUserGwResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
