// 2017-11-15 11:43:13.25091 -0800 PST m=+18.525195607
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeSubnetResp struct {
	AvailableIPNum   int64  `json:"availableIPNum"`
	CidrBlock        string `json:"cidrBlock"`
	Code             int64  `json:"code"`
	CodeDesc         string `json:"codeDesc"`
	Message          string `json:"message"`
	RouteTableID     string `json:"routeTableId"`
	SubnetCreateTime string `json:"subnetCreateTime"`
	SubnetID         string `json:"subnetId"`
	SubnetName       string `json:"subnetName"`
	TotalIPNum       int64  `json:"totalIPNum"`
	ZoneID           int64  `json:"zoneId"`
}

// Implement https://cloud.tencent.com/document/api/215/1311
func DescribeSubnet(options ...string) (*DescribeSubnetResp, error) {
	resp, err := DoAction("DescribeSubnet", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeSubnetResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *DescribeSubnetResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
