// 2017-11-28 14:24:17.590182 -0800 PST m=+282.327734738
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type InquiryNatPriceResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
	Price    struct {
		Device  int64 `json:"device"`
		Traffic int64 `json:"traffic"`
	} `json:"price"`
}

// Implement https://cloud.tencent.com/document/api/215/4091
func InquiryNatPrice(options ...string) (*InquiryNatPriceResp, error) {
	resp, err := DoAction("InquiryNatPrice", options...)
	if err != nil {
		return nil, err
	}
	var s InquiryNatPriceResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *InquiryNatPriceResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
