// 2018-01-09 09:23:01.68171 -0800 PST m=+63.007491490
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ModifyUserGwResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/215/5118
func (c *VpcClient) ModifyUserGw(options ...string) (*ModifyUserGwResp, error) {
	resp, err := c.DoAction("ModifyUserGw", options...)
	if err != nil {
		return nil, err
	}
	var s ModifyUserGwResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func ModifyUserGw(options ...string) (*ModifyUserGwResp, error) {
	return DefaultClient.ModifyUserGw(options...)
}

func (r *ModifyUserGwResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
