// 2017-11-28 16:37:14.726897 -0800 PST m=+318.389295518
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ModifyNatGatewayResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/215/4086
func ModifyNatGateway(options ...string) (*ModifyNatGatewayResp, error) {
	resp, err := DoAction("ModifyNatGateway", options...)
	if err != nil {
		return nil, err
	}
	var s ModifyNatGatewayResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *ModifyNatGatewayResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
