// 2018-01-09 09:22:44.992615 -0800 PST m=+46.318366133
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ModifyNetworkAclEntryResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/215/1444
func (c *VpcClient) ModifyNetworkAclEntry(options ...string) (*ModifyNetworkAclEntryResp, error) {
	resp, err := c.DoAction("ModifyNetworkAclEntry", options...)
	if err != nil {
		return nil, err
	}
	var s ModifyNetworkAclEntryResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func ModifyNetworkAclEntry(options ...string) (*ModifyNetworkAclEntryResp, error) {
	return DefaultClient.ModifyNetworkAclEntry(options...)
}

func (r *ModifyNetworkAclEntryResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
