// 2017-11-14 00:10:13.880372 -0800 PST m=+12.554054273
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ModifyVpcAttributeResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/215/1310
func ModifyVpcAttribute(options ...string) (*ModifyVpcAttributeResp, error) {
	resp, err := DoAction("ModifyVpcAttribute", options...)
	if err != nil {
		return nil, err
	}
	var s ModifyVpcAttributeResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func (r *ModifyVpcAttributeResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
