// 2018-01-09 09:22:50.214783 -0800 PST m=+51.540543480
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package vpc

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type ModifySubnetAttributeResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Message  string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/215/1313
func (c *VpcClient) ModifySubnetAttribute(options ...string) (*ModifySubnetAttributeResp, error) {
	resp, err := c.DoAction("ModifySubnetAttribute", options...)
	if err != nil {
		return nil, err
	}
	var s ModifySubnetAttributeResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func ModifySubnetAttribute(options ...string) (*ModifySubnetAttributeResp, error) {
	return DefaultClient.ModifySubnetAttribute(options...)
}

func (r *ModifySubnetAttributeResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
