// 2018-01-09 09:16:07.5601 -0800 PST m=+3.090830995
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package eip

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeEipQuotaResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		CurrentEipNum        int64 `json:"currentEipNum"`
		DailyAllocWanIPCount int64 `json:"dailyAllocWanIpCount"`
		DailyAllocWanIPQuota int64 `json:"dailyAllocWanIpQuota"`
		DailyApplyCount      int64 `json:"dailyApplyCount"`
		DailyApplyQuota      int64 `json:"dailyApplyQuota"`
		EipNumQuota          int64 `json:"eipNumQuota"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api/213/1378
func (c *EipClient) DescribeEipQuota(options ...string) (*DescribeEipQuotaResp, error) {
	resp, err := c.DoAction("DescribeEipQuota", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeEipQuotaResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeEipQuota(options ...string) (*DescribeEipQuotaResp, error) {
	return DefaultClient.DescribeEipQuota(options...)
}

func (r *DescribeEipQuotaResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
