// 2018-01-09 09:16:06.015634 -0800 PST m=+1.546361744
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package eip

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeEipResp struct {
	Code     int64  `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		EipSet []interface{} `json:"eipSet"`
	} `json:"data"`
	Message    string `json:"message"`
	TotalCount int64  `json:"totalCount"`
}

// Implement https://cloud.tencent.com/document/api/213/1379
func (c *EipClient) DescribeEip(options ...string) (*DescribeEipResp, error) {
	resp, err := c.DoAction("DescribeEip", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeEipResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeEip(options ...string) (*DescribeEipResp, error) {
	return DefaultClient.DescribeEip(options...)
}

func (r *DescribeEipResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
