// 2018-01-09 09:19:56.566218 -0800 PST m=+1.941210151
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package img

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeImagesResp struct {
	Response struct {
		ImageSet []struct {
			Architecture     string      `json:"Architecture"`
			CreatedTime      interface{} `json:"CreatedTime"`
			ImageCreator     interface{} `json:"ImageCreator"`
			ImageDescription string      `json:"ImageDescription"`
			ImageID          string      `json:"ImageId"`
			ImageName        string      `json:"ImageName"`
			ImageSize        int64       `json:"ImageSize"`
			ImageSource      string      `json:"ImageSource"`
			ImageState       string      `json:"ImageState"`
			ImageType        string      `json:"ImageType"`
			OsName           string      `json:"OsName"`
			Platform         string      `json:"Platform"`
		} `json:"ImageSet"`
		RequestID  string `json:"RequestId"`
		TotalCount int64  `json:"TotalCount"`
	} `json:"Response"`
}

// Implement https://cloud.tencent.com/document/api/213/9418
func (c *ImgClient) DescribeImages(options ...string) (*DescribeImagesResp, error) {
	resp, err := c.DoAction("DescribeImages", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeImagesResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeImages(options ...string) (*DescribeImagesResp, error) {
	return DefaultClient.DescribeImages(options...)
}

func (r *DescribeImagesResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
